const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
(async()=>{const {preparePages}=await import('../scripts/prepare-pages.mjs'),artifact=path.join(out,'site');preparePages(root,artifact);
const prefix='/fcim-indoor-map/',server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"synthetic release availability test"}');return;}
if(!u.pathname.startsWith(prefix)){res.writeHead(404);res.end();return;}const name=decodeURIComponent(u.pathname.slice(prefix.length))||'index.html';if(name.includes('/')||name.includes('\\')||!fs.readdirSync(artifact).includes(name)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(path.join(artifact,name)));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true}),results=[],errors=[],requests=[];
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
try{for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:320,height:740}]){const context=await browser.newContext({viewport,isMobile:viewport.width<900,hasTouch:viewport.width<900}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>requests.push({url:r.url(),status:r.status()}));await page.addInitScript(apiBaseUrl=>{window.FCIM_TIMETABLE_CONFIG={apiBaseUrl};},origin);
await check('Project URL initialization and qualified unavailable state '+viewport.width,async()=>{await page.goto(origin+prefix);await page.waitForFunction(()=>document.querySelector('#scheduleSummary').textContent.includes('503'));assert.equal((await page.evaluate(()=>FCIM_MAP_APP.getScheduleState())).source,'real');assert.equal(await page.locator('.scheduled-mine,.scheduled-other').count(),0);await page.screenshot({path:path.join(out,'synthetic-unavailable-'+viewport.width+'.png')});});
await check('Demo remains usable during producer failure '+viewport.width,async()=>{await page.locator('#sourceSelect').selectOption('demo');assert.equal((await page.evaluate(()=>FCIM_MAP_APP.getScheduleState())).source,'demo');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'local-demo-'+viewport.width+'.png')});});
await check('Direct floor 6 fragment and reload '+viewport.width,async()=>{await page.goto(origin+prefix+'#floor=6');assert.equal(await page.locator('[data-id="B3-F6-N01"]').count(),1);await page.reload();assert.equal(await page.locator('[data-id="B3-F6-N01"]').count(),1);assert.equal(new URL(page.url()).hash,'#floor=6');});
await check('Floor navigation, search, zoom and composite details '+viewport.width,async()=>{await page.goto(origin+prefix+'#floor=1');await page.locator('#sourceSelect').selectOption('demo');await page.locator('#searchInput').fill('103');await page.locator('#searchInput').press('Enter');assert.deepEqual(await page.evaluate(()=>FCIM_MAP_APP.getLogicalSelection().spaceIds),['B3-F1-S10','B3-F1-S11']);const before=await page.locator('#map').getAttribute('viewBox');await page.locator('#zoomIn').click();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),before);await page.locator('#zoomReset').click();if(viewport.width<900){const target=page.locator('[data-id="B3-F1-S10"]'),box=await target.boundingBox();await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);}await page.screenshot({path:path.join(out,'local-details-'+viewport.width+'.png')});});
await context.close();}
await check('Published artifact file:// demo has no remote dependency',async()=>{const page=await browser.newPage({viewport:{width:1440,height:900}}),remote=[];page.on('request',r=>{if(r.url().startsWith('http'))remote.push(r.url());});await page.goto(pathToFileURL(path.join(artifact,'index.html')).href+'#floor=1');assert.equal((await page.evaluate(()=>FCIM_MAP_APP.getScheduleState())).source,'demo');assert.deepEqual(remote,[]);await page.screenshot({path:path.join(out,'local-file-demo.png')});await page.close();});
await check('Every project-path runtime asset loads and no runtime exception occurs',async()=>{assert.deepEqual(errors,[]);assert.ok(requests.some(r=>r.url.includes(prefix+'timetable-ui.js')));assert.ok(requests.filter(r=>r.url.includes(prefix)).every(r=>r.status===200));});
}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({basis:'LOCAL packaged static runtime at /fcim-indoor-map/; API 503 is SYNTHETIC FAILURE TEST; mobile is browser emulation',browser:browser.version(),results,errors,requests},null,2)+'\n');await browser.close();server.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})();
