// Real SVG interaction and pixel preservation; photographs stay outside this repository.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]);
fs.mkdirSync(out,{recursive:true});
const files=['index.html','map-data.js','room-contract.js','schedule-engine.js','schedule-fixture.js','map-semantics.js','room-identification.js'];
const results=[],errors=[],KEY='fcim-indoor-map/utm-b3/bindings';let browser,page,context,url;
async function fresh(mobile=false){if(context)await context.close();context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile,acceptDownloads:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(url);await page.locator('#scheduleDate').fill('2027-06-28');await page.locator('#scheduleDate').dispatchEvent('change');}
async function floor(n){await page.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');assert.equal(await page.locator('[data-id="'+id+'"].sel').count(),1);}
async function point(x,y){return page.locator('#map').evaluate((s,{x,y})=>{const p=new DOMPoint(x,y).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},{x,y});}
async function test(name,fn){const start=errors.length;try{const evidence=await fn();assert.equal(errors.length,start,'No browser exceptions');results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
async function exported(source,n,box){const p=await browser.newPage({viewport:{width:2000,height:700}});await p.goto(pathToFileURL(path.join(source,'index.html')).href);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,box)=>{const c=s.cloneNode(true),os=[s,...s.querySelectorAll('*')],cs=[c,...c.querySelectorAll('*')];os.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','pointer-events'])cs[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width','2000');c.setAttribute('height','615');c.setAttribute('viewBox',box||'-33.333333 -83.333333 1111.111111 341.666667');c.style='width:2000px;height:615px;background:white';return c.outerHTML;},box);await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.screenshot();await p.close();return {svg,png};}
(async()=>{
 const server=http.createServer((req,res)=>{const f=new URL(req.url,'http://local').pathname.slice(1)||'index.html';if(f==='favicon.ico'){res.writeHead(204);return res.end();}if(!files.includes(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,f)));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;
 try{
  browser=await chromium.launch({channel:'chrome',headless:true});
  await test('Floor 3 cells remain selectable by keyboard and physical pointer hit',async()=>{await fresh();await floor(3);for(const [id,x,y] of [['B3-F3-S01',24,141.5],['B3-F3-S02',60,121],['B3-F3-S03',60,147.5]]){await select(id);const p=await point(x,y);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+id+'"].sel').count(),1);}await page.screenshot({path:path.join(out,'floor3-desktop.png')});});
  await test('Unresolved floor 3 passage and bottom strip acquire no invented selection ID',async()=>{await fresh();await floor(3);for(const [x,y] of [[45,145],[60,168]]){const p=await point(x,y),id=await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-id]')?.dataset.id,p);assert.equal(id,undefined);}});
  await test('Valid bindings for all three cells survive reload, search and export',async()=>{await fresh();const bindings=Object.fromEntries([1,2,3].map(i=>{const id='B3-F3-S0'+i;return [id,{spaceId:id,floorLevel:3,roomNumber:'30'+i,fullNumber:'3-30'+i,method:'manual',updatedAt:'2026-10-08T05:00:00Z'}];}));const raw=JSON.stringify({schemaVersion:1,buildingId:'utm-b3',mapDataVersion:'2026-10-08.1',bindings});await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();for(let i=1;i<=3;i++){await page.locator('#searchInput').fill('3-30'+i);await page.locator('#searchInput').press('Enter');assert.equal(await page.locator('[data-id="B3-F3-S0'+i+'"].sel.bound').count(),1);}assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);const data=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.deepEqual(data.bindings.map(b=>b.spaceId).sort(),Object.keys(bindings));});
  await test('Floor 7 flights and landing render once and every artwork element ignores pointers',async()=>{await fresh();await floor(7);const art=page.locator('[data-stair-art="B3-F7-STW"]');assert.equal(await art.count(),1);assert.equal(await art.locator('.geo-flight').count(),2);assert.equal(await art.locator('.geo-landing').count(),1);assert.ok((await art.evaluateAll(gs=>gs.flatMap(g=>[g,...g.querySelectorAll('*')].map(e=>getComputedStyle(e).pointerEvents)))).every(v=>v==='none'));assert.equal(await page.locator('[data-id="B3-F7-STW"] .x').count(),0);await select('B3-F7-STW');await select('B3-F7-HW');});
  await test('Upper flight remains an actual hall hit; no selectable stair region expands',async()=>{await fresh();await floor(7);for(const [x,y,id] of [[265,120,'B3-F7-HW'],[250,125,'B3-F7-HW'],[220,162,'B3-F7-STW']]){const p=await point(x,y);assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-id]')?.dataset.id,p),id);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+id+'"].sel').count(),1);}await page.screenshot({path:path.join(out,'floor7-desktop.png')});});
  for(const n of [3,7])await test('Mobile floor '+n+' touch selection, zoom and pan keep geometry operational',async()=>{await fresh(true);await floor(n);await select(n===3?'B3-F3-S03':'B3-F7-HW');await page.waitForTimeout(350);const before=await page.locator('#map').getAttribute('viewBox');await page.locator('#zoomIn').click();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),before);const p=await point(n===3?60:265,n===3?147.5:120);await page.touchscreen.tap(p.x,p.y);assert.equal(await page.locator('[data-id="'+(n===3?'B3-F3-S03':'B3-F7-HW')+'"].sel').count(),1);await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'floor'+n+'-mobile-zoom.png')});const cdp=await context.newCDPSession(page),box=await page.locator('#mapwrap').boundingBox(),y=box.y+box.height*.5,start=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:215,y:y+20,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),start);return {device:'CDP touch emulation, 390x844'};});
  await test('Unchanged floors and unrelated local regions are pixel-identical',async()=>{for(const n of [2,4,5,6]){assert.deepEqual((await exported(root,n)).png,(await exported(baseline,n)).png,'Floor '+n);}for(const [n,box] of [[3,'75 0 925 175'],[7,'305 0 695 175']])assert.deepEqual((await exported(root,n,box)).png,(await exported(baseline,n,box)).png,'Unaffected region '+n);});
  await test('Actual before/after SVG exports generated without runtime or route errors',async()=>{for(const n of [3,7])for(const [tag,source] of [['before',baseline],['after',root]]){const {svg,png}=await exported(source,n);fs.writeFileSync(path.join(out,'floor'+n+'-'+tag+'.svg'),svg);fs.writeFileSync(path.join(out,'floor'+n+'-'+tag+'.png'),png);}await fresh();assert.equal(await page.locator('#routeToggle,#layerRoute,#routeFromHere,#routeToHere').count(),0);});
 }finally{const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts,results,errors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));if(context)await context.close();if(browser)await browser.close();await new Promise(r=>server.close(r));}
 process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(e=>{console.error(e);process.exitCode=2;});
