const assert=require('assert/strict'),fs=require('fs');
const map=require('./geo02-contract.cjs').preGeoModel(require('../map-data.js')),gate=require('./geo01-contract.cjs'),before=gate.baselineModel();
const room=require('../room-contract.js'),semantics=require('../map-semantics.js'),results=[];
const floor=(m,n)=>m.floors.find(f=>f.level===n),f3=floor(map,3),f7=floor(map,7);
const cells=f3.spaces.filter(s=>/^B3-F3-S0[123]$/.test(s.id));
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const area=p=>Math.abs(p.reduce((n,a,i)=>{const b=p[(i+1)%p.length];return n+a[0]*b[1]-b[0]*a[1];},0))/2;
function on(p,a,b){return Math.abs(cross(a,b,p))<1e-8&&p[0]>=Math.min(a[0],b[0])&&p[0]<=Math.max(a[0],b[0])&&p[1]>=Math.min(a[1],b[1])&&p[1]<=Math.max(a[1],b[1]);}
function inside(p,poly){let hit=false;poly.forEach((a,i)=>{const b=poly[(i+1)%poly.length];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;});return hit||poly.some((a,i)=>on(p,a,poly[(i+1)%poly.length]));}
function valid(poly,allowInheritedTouch=false){assert.ok(poly.length>=3&&area(poly)>0);poly.forEach((p,i)=>{assert.ok(p.length===2&&p.every(Number.isFinite));assert.notDeepEqual(p,poly[(i+1)%poly.length]);});for(let i=0;i<poly.length;i++)for(let j=i+1;j<poly.length;j++){if(j===i+1||(i===0&&j===poly.length-1))continue;const a=poly[i],b=poly[(i+1)%poly.length],c=poly[j],d=poly[(j+1)%poly.length];assert.ok(!(cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0),'crossing edges');if(!allowInheritedTouch)assert.ok(!on(a,c,d)&&!on(b,c,d)&&!on(c,a,b)&&!on(d,a,b),'nonadjacent touching edges');}}
// Exact positive-area intersections for the existing orthogonal coordinate system.
function rectangles(poly){const xs=[...new Set(poly.map(p=>p[0]))].sort((a,b)=>a-b),rects=[];poly.forEach((a,i)=>{const b=poly[(i+1)%poly.length];assert.ok(a[0]===b[0]||a[1]===b[1],'orthogonal polygon');});for(let i=1;i<xs.length;i++){const x=(xs[i-1]+xs[i])/2,ys=[];poly.forEach((a,j)=>{const b=poly[(j+1)%poly.length];if(a[1]===b[1]&&x>Math.min(a[0],b[0])&&x<Math.max(a[0],b[0]))ys.push(a[1]);});ys.sort((a,b)=>a-b);for(let j=0;j<ys.length;j+=2)rects.push([xs[i-1],ys[j],xs[i],ys[j+1]]);}return rects;}
function overlap(a,b){let sum=0;for(const r of rectangles(a))for(const s of rectangles(b))sum+=Math.max(0,Math.min(r[2],s[2])-Math.max(r[0],s[0]))*Math.max(0,Math.min(r[3],s[3])-Math.max(r[1],s[1]));return sum;}
function test(name,fn){try{results.push({name,status:'PASS',evidence:fn()});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
test('Source changes are exhaustively allowlisted against immutable commit',()=>gate.validatePreservation());
test('All 194 IDs, floor assignments and space ordering remain identical',()=>{assert.equal(map.floors.flatMap(f=>f.spaces).length,194);assert.deepEqual(map.floors.map(f=>[f.id,f.spaces.map(s=>[s.id,s.floorId])]),before.floors.map(f=>[f.id,f.spaces.map(s=>[s.id,s.floorId])]));});
test('Polygons are valid; exactly four inherited touching spurs stay byte-preserved',()=>{let count=0;const inherited=['B3-F2-N08','B3-F3-N08','B3-F4-N08','B3-F5-N07'];for(const f of map.floors){const polygons=[f.geometry.outline,f.geometry.corridor,...f.spaces.map(s=>s.polygon),...f.geometry.verticals.flatMap(v=>[v.polygon,...(v.innerShaft?[v.innerShaft]:[]),...(v.visualStair?[v.visualStair.landing,...v.visualStair.flights]:[])]),...f.geometry.features.flatMap(ft=>[...(ft.polygon?[ft.polygon]:[]),...(ft.flights||[])])];polygons.forEach(p=>{const legacy=f.spaces.find(s=>s.polygon===p&&inherited.includes(s.id));if(legacy)assert.deepEqual(p,floor(before,f.level).spaces.find(s=>s.id===legacy.id).polygon);valid(p,!!legacy);count++;});}return {polygons:count,inheritedTouchingSpurs:inherited};});
test('All existing space label points remain inside their polygons',()=>{map.floors.forEach(f=>f.spaces.forEach(s=>assert.ok(inside(s.labelPoint,s.polygon),s.id)));});
test('Corrected cells share an entire dividing edge and east wall with S04',()=>{const a=cells[1].polygon,b=cells[2].polygon,s4=f3.spaces.find(s=>s.id==='B3-F3-S04').polygon;assert.deepEqual(a.slice(2).reverse(),b.slice(0,2));assert.equal(a[1][0],s4[0][0]);assert.equal(b[1][0],s4[0][0]);assert.equal(overlap(a,b),0);});
test('No corrected polygon overlaps any room, vertical or corridor',()=>{for(const s of cells){for(const t of f3.spaces.filter(t=>t.id!==s.id))assert.equal(overlap(s.polygon,t.polygon),0,s.id+' / '+t.id);assert.equal(overlap(s.polygon,f3.geometry.corridor),0);for(const v of f3.geometry.verticals)assert.equal(overlap(s.polygon,v.polygon),0);}return {areaBefore:cells.map(s=>area(floor(before,3).spaces.find(x=>x.id===s.id).polygon)),areaAfter:cells.map(s=>area(s.polygon))};});
test('Relative dimensions improve without treating photo approximations as exact',()=>{for(const s of cells.slice(1)){const p=s.polygon,old=floor(before,3).spaces.find(x=>x.id===s.id).polygon,w=p[1][0]-p[0][0],depth=p[2][1]-p[1][1];assert.ok(w<old[1][0]-old[0][0]&&w>=19&&w<=25);assert.ok(depth>=23&&depth<=30);}assert.ok(Math.max(...cells[2].polygon.map(p=>p[1]))<170);});
test('Doors lie on their referenced cell boundaries, retain IDs and uncertain access',()=>{for(const s of cells){const d=f3.geometry.doors.find(d=>d.spaceId===s.id);assert.ok(s.polygon.some((a,i)=>on([d.x,d.y],a,s.polygon[(i+1)%s.polygon.length])));assert.equal(d.id,s.id+'-D1');assert.equal(d.to,floor(before,3).geometry.doors.find(x=>x.id===d.id).to);assert.equal(d.access,'unknown');if(s!==cells[0])assert.equal(d.connectionVerification,'unverified');}assert.match(cells[0].notes,/не присвоены S01/);});
test('Bindings for every affected room resolve without changing identity or numbering',()=>{const parse=room.createParser(map,'3'),resolve=room.createResolver(map,parse);cells.forEach((s,i)=>{const r=resolve({source:'timetable',buildingId:'utm-b3',room:'3-30'+(i+1)},{bindings:[{spaceId:s.id,roomNumber:'30'+(i+1),verification:'verified'}]});assert.equal(r.spaceId,s.id);assert.equal(s.roomNumber,null);});assert.deepEqual(map.confirmedRoomNumbers,before.confirmedRoomNumbers);});
test('Only F7 STW has decorative flights; all selectable stair/hall polygons unchanged',()=>{const vs=map.floors.flatMap(f=>f.geometry.verticals).filter(v=>v.visualStair);assert.equal(vs.length,1);assert.equal(vs[0].id,'B3-F7-STW');assert.deepEqual(f7.spaces,floor(before,7).spaces);map.floors.forEach((f,i)=>f.geometry.verticals.forEach((v,j)=>assert.deepEqual(v.polygon,before.floors[i].geometry.verticals[j].polygon)));const art=vs[0].visualStair;assert.equal(art.flights.length,2);assert.ok(art.flights[0][1][0]-art.flights[0][0][0]>art.flights[1][1][0]-art.flights[1][0][0]);assert.equal(overlap(art.landing,art.flights[0]),0);assert.equal(overlap(art.landing,art.flights[1]),0);const hall=f7.spaces.find(s=>s.id==='B3-F7-HW');assert.ok(overlap(art.flights[1],hall.polygon)>0);for(const s of f7.spaces.filter(s=>s!==hall))for(const p of [art.landing,...art.flights])assert.equal(overlap(p,s.polygon),0);});
test('Protected floors, all graph data and uncertainty semantics stay unchanged',()=>{for(const n of [2,4,5,6])assert.deepEqual(floor(map,n),floor(before,n));assert.deepEqual(map.floors.map(f=>f.navigation),before.floors.map(f=>f.navigation));assert.deepEqual(map.verticalLinks,before.verticalLinks);assert.equal(map.schemaVersion,before.schemaVersion);assert.equal(map.dataVersion,before.dataVersion);const facilities=semantics.facilities(map);assert.ok(facilities.every(f=>f.operational===undefined||f.operational==='unknown'));assert.equal(facilities.find(f=>f.kind==='toilet').evidence,'unknown');});
const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify({counts,results},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));process.exitCode=counts.FAIL?1:0;
