const fs=require('fs'),assert=require('assert/strict'),map=require('../map-data.js'),gate=require('./geo02-contract.cjs'),g=require('./geo02-geometry.cjs'),sem=require('../map-semantics.js'),room=require('../room-contract.js');
const f=map.floors.find(f=>f.id==='B3-F1'),results=[];
function test(name,fn){try{results.push({name,status:'PASS',evidence:fn()});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
test('Immutable baseline and exact source allowlist preserve six floors and local reports',()=>gate.validatePreservation());
test('Only justified first-floor identities added, deterministic order, no duplicate pending floor',()=>{assert.deepEqual(map.floors.map(f=>f.level),[1,2,3,4,5,6,7]);assert.equal(map.plannedFloors.length,1);assert.equal(map.plannedFloors[0].id,'B3-FD');const old=gate.baselineModel(),all=map.floors.flatMap(f=>f.spaces),ids=all.map(s=>s.id);assert.equal(new Set(ids).size,ids.length);assert.equal(all.length,194+28);assert.deepEqual(f.spaces.map(s=>s.id),require('../GEO-02_CHANGES.json').newSpaceIds);for(const s of old.floors.flatMap(f=>f.spaces))assert.deepEqual(all.find(t=>t.id===s.id),s);return {old:194,new:28,total:222};});
test('New observations retain provenance, source region, confidence, unknown purpose and null numbers',()=>{assert.equal(f.source.photo,'floor1.jpg');assert.equal(f.source.sha256,'fa2e31d1d0fc14f554bddfef8a6226425e1f6d780f28689a7882beb646dbd5b9');assert.deepEqual(f.source.dimensions,[2560,1710]);for(const s of f.spaces){assert.equal(s.floorId,f.id);assert.equal(s.roomNumber,null);assert.equal(s.source,'floor1.jpg');assert.equal(s.verification,'observed');assert.ok(['medium','low'].includes(s.confidence));assert.ok(s.sourceRegion.bounds.every(Number.isFinite));assert.equal(s.type,s.kind==='room'?'unknown':'circulation');}});
test('Every new polygon has finite vertices, nonzero area and no crossings or self-touching',()=>{let count=0;for(const p of [f.geometry.outline,f.geometry.corridor,...f.spaces.map(s=>s.polygon),...f.geometry.verticals.flatMap(v=>[v.polygon,...(v.innerShaft?[v.innerShaft]:[]),...(v.stairDrawing?[v.stairDrawing.landing,...v.stairDrawing.flights]:[])]),...f.geometry.features.filter(ft=>ft.polygon).map(ft=>ft.polygon)]){g.valid(p);count++;}return {polygons:count};});
test('Labels are strictly inside their spaces and all polygons lie within the irregular exterior',()=>{for(const s of f.spaces){assert.ok(g.inside(s.labelPoint,s.polygon),s.id);assert.ok(!s.polygon.some((a,i)=>g.on(s.labelPoint,a,s.polygon[(i+1)%s.polygon.length])),s.id+' strict label');}for(const p of [f.geometry.corridor,...f.spaces.map(s=>s.polygon),...f.geometry.verticals.map(v=>v.polygon),...f.geometry.features.filter(ft=>ft.polygon).map(ft=>ft.polygon)])for(const point of p)assert.ok(g.inside(point,f.geometry.outline),point);assert.ok(Math.max(...f.geometry.outline.map(v=>v[1]))>175);});
test('No positive-area space-space, space-corridor, space-stair or space-feature overlap',()=>{let pairs=0;for(let i=0;i<f.spaces.length;i++){const s=f.spaces[i];for(const t of f.spaces.slice(i+1)){assert.equal(g.overlap(s.polygon,t.polygon),0,s.id+' / '+t.id);pairs++;}for(const [id,p] of [['corridor',f.geometry.corridor],...f.geometry.verticals.map(v=>[v.id,v.polygon]),...f.geometry.features.filter(v=>v.polygon).map(v=>[v.id,v.polygon])])assert.equal(g.overlap(s.polygon,p),0,s.id+' / '+id);}for(const v of f.geometry.verticals)assert.equal(g.overlap(v.polygon,f.geometry.corridor),0,v.id);return {spacePairs:pairs};});
test('Shared room partitions and internal doors agree without invented corridor crossings',()=>{for(const d of f.geometry.doors){const s=f.spaces.find(s=>s.id===d.spaceId);assert.ok(s,d.id);assert.ok(s.polygon.some((a,i)=>g.on([d.x,d.y],a,s.polygon[(i+1)%s.polygon.length])),d.id+' boundary');const target=d.to==='corridor'?f.geometry.corridor:f.spaces.find(s=>s.id===d.to)?.polygon;assert.ok(target,d.id+' target');assert.ok(target.some((a,i)=>g.on([d.x,d.y],a,target[(i+1)%target.length])),d.id+' shared boundary');assert.equal(d.access,'unknown');assert.equal(d.connectionVerification,'unverified');assert.equal(d.source,'floor1.jpg');assert.ok(['horizontal','vertical'].includes(d.orientation));}assert.equal(new Set(f.geometry.doors.map(d=>d.id)).size,f.geometry.doors.length);assert.ok(!Object.hasOwn(f.geometry,'corridorBand'));});
test('Stair drawings and shaft symbols are geometrically contained and operationally unknown',()=>{for(const v of f.geometry.verticals){assert.equal(v.operational,'unknown');assert.equal(v.access,'unknown');if(v.stairDrawing){for(const p of [v.stairDrawing.landing,...v.stairDrawing.flights])for(const pt of p)assert.ok(g.inside(pt,v.polygon),v.id);for(let i=0;i<v.stairDrawing.flights.length;i++)for(const p of [v.stairDrawing.landing,...v.stairDrawing.flights.slice(i+1)])assert.equal(g.overlap(v.stairDrawing.flights[i],p),0,v.id+' drawing overlap');}if(v.innerShaft)for(const pt of v.innerShaft)assert.ok(g.inside(pt,v.polygon));}const a=sem.facilities(map).filter(x=>x.floorId===f.id);assert.equal(a.filter(x=>x.kind==='unknown-shaft').length,3);assert.equal(a.filter(x=>x.kind==='elevator-shaft'||x.kind==='toilet').length,0);assert.ok(a.filter(x=>x.kind==='opening').every(x=>x.identityEvidence==='unknown'&&x.access==='unknown'));assert.equal(sem.facilities(map).find(x=>x.id==='B3-ENTRANCES-UNKNOWN').evidence,'unknown');});
test('Archived graph is exact; first floor adds no node, edge, shaft connection or vertical link',()=>{const b=gate.baselineModel();assert.deepEqual(map.floors.filter(f=>f.level>1).map(f=>f.navigation),b.floors.map(f=>f.navigation));assert.deepEqual(map.verticalLinks,b.verticalLinks);assert.deepEqual(f.navigation,{status:'disabled',nodes:[],edges:[]});});
test('Resolver never derives first-floor geometry from room digit; manual records stay unverified',()=>{const parse=room.createParser(map,'3'),resolve=room.createResolver(map,parse),lesson={room:'3-101',source:'timetable',buildingId:'utm-b3'},binding={roomNumber:'101',spaceId:'B3-F1-N01',method:'manual'};assert.equal(resolve(lesson).status,'unmapped');assert.equal(resolve(lesson,{bindings:[binding]}).status,'unverified-binding');assert.equal(resolve(lesson,{bindings:[{...binding,verification:'verified'}]}).spaceId,'B3-F1-N01');assert.equal(resolve({...lesson,source:'mock'},{bindings:[binding]}).spaceId,null);assert.ok(!require('../schedule-fixture.js').demoAssociations.some(b=>b.spaceId.startsWith('B3-F1-')));});
test('Store compatibility version retained while additive geometry revision is explicit',()=>{assert.equal(map.dataVersion,gate.baselineModel().dataVersion);assert.equal(map.schemaVersion,'1.0.0');assert.equal(map.geometryRevision,'2026-10-09.GEO-02');});
test('Independent predicates reject touching/crossed polygons and detect fractional irregular overlap',()=>{assert.throws(()=>g.valid([[0,0],[2,2],[0,2],[2,0]]));assert.throws(()=>g.valid([[0,0],[2,0],[2,2],[1,0],[0,2]]));assert.equal(g.overlap([[0,0],[2,0],[0,2]],[[1,0],[2,0],[2,2],[1,2]]),0.5);});
const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify({counts,results},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));process.exitCode=counts.FAIL?1:0;
