// Actual Chrome SVG, isolated storage and CDP touch. No production profile access.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]),map=require('../map-data.js'),f=map.floors.find(f=>f.level===1),KEY='fcim-indoor-map/utm-b3/bindings';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[],consoleErrors=[];let browser,context,page,accept=true;
async function fresh(viewport={width:1440,height:900},mobile=false){if(context)await context.close();context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());await page.goto(pathToFileURL(path.join(root,'index.html')).href+'#floor=1');}
async function floor(n){await page.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');assert.equal(await page.locator('[data-id="'+id+'"].sel').count(),1);await page.waitForTimeout(350);}
async function point(pt){return page.locator('#map').evaluate((s,pt)=>{const p=new DOMPoint(...pt).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},pt);}
async function search(s){await page.locator('#searchInput').fill(s);await page.locator('#searchInput').press('Enter');}
async function bind(id,n){await floor(1);await select(id);if(await page.locator('#editToggle').getAttribute('aria-pressed')!=='true')await page.locator('#editToggle').click();await page.locator('#numInput').fill(n);await page.locator('#numInput').press('Enter');}
async function exportData(){const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);return JSON.parse(fs.readFileSync(await d.path(),'utf8'));}
async function upload(d){await page.locator('#importFile').setInputFiles({name:'geo02-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await page.waitForTimeout(150);}
async function test(name,fn){const e=errors.length,c=consoleErrors.length;try{results.push({name,status:'PASS',evidence:await fn()});assert.equal(errors.length,e);assert.equal(consoleErrors.length,c);}catch(err){if(results.at(-1)?.name===name)results.pop();results.push({name,status:'FAIL',error:err.stack});}console.log(results.at(-1).status,name);}
async function exported(source,n,save){const p=await browser.newPage({viewport:{width:2080,height:600}});await p.goto(pathToFileURL(path.join(source,'index.html')).href+'#floor='+n);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,n)=>{const c=s.cloneNode(true),a=[s,...s.querySelectorAll('*')],b=[c,...c.querySelectorAll('*')];a.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','pointer-events'])b[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width','2080');c.setAttribute('height','440');c.setAttribute('viewBox',n===1?'-20 -15 1040 220':'-30 -45 1100 285');c.setAttribute('xmlns','http://www.w3.org/2000/svg');c.style='width:2080px;height:440px';return c.outerHTML;},n);await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.locator('svg').screenshot({omitBackground:true});if(save){fs.writeFileSync(path.join(out,'floor'+n+'.svg'),svg);fs.writeFileSync(path.join(out,'floor'+n+'.png'),png);}await p.close();return png;}
(async()=>{try{browser=await chromium.launch({channel:'chrome',headless:true});
await test('Standalone first-floor deep link, seven ready selectors and basement pending',async()=>{await fresh();assert.equal(await page.locator('#floorNav .active').innerText(),'1');assert.equal(await page.locator('#layerSpaces polygon').count(),28);for(let n=1;n<=7;n++){await floor(n);assert.equal(await page.locator('#floorNav .active').innerText(),String(n));assert.equal(await page.locator('#layerSpaces polygon').count(),map.floors.find(f=>f.level===n).spaces.length);}await floor('D');assert.equal(await page.locator('#floorNav .active').innerText(),'7');assert.equal(await page.locator('#floorNav button.pending').count(),1);await floor(1);await page.screenshot({path:path.join(out,'desktop-overview.png')});});
await test('North, south, irregular cells and halls support keyboard, hover and real pointer hits',async()=>{await fresh();for(const id of ['N01','N07','S06','S07','S08','S14','HW','LH','HC','HE']){const s=f.spaces.find(s=>s.id==='B3-F1-'+id);await select(s.id);const p=await point(s.labelPoint);await page.mouse.move(p.x,p.y);assert.equal(await page.locator('[data-id="'+s.id+'"]:hover').count(),1);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+s.id+'"].sel').count(),1);assert.match(await page.locator('#panel').innerText(),new RegExp(s.id));}await page.screenshot({path:path.join(out,'desktop-selected.png')});});
await test('First-floor shafts disclose unknown identity/operation; halls cannot receive classroom numbers',async()=>{await fresh();await select('B3-F1-SH1');assert.match(await page.locator('#panel').innerText(),/Символ шахты.*назначение неизвестно/);assert.match(await page.locator('#panel').innerText(),/operation: unknown/);await page.locator('#editToggle').click();await select('B3-F1-HC');assert.equal(await page.locator('#numInput').count(),0);assert.equal(await page.locator('[data-facility="toilet"]').count(),0);assert.ok((await page.locator('[data-stair-art]').evaluateAll(gs=>gs.flatMap(g=>[g,...g.querySelectorAll('*')].map(e=>getComputedStyle(e).pointerEvents)))).every(x=>x==='none'));});
await test('No fabricated first-floor schedule or numbered search association',async()=>{await fresh();await page.locator('#allMode').click();await floor(1);assert.equal(await page.locator('.sp.scheduled-mine,.sp.scheduled-other,.sp.schedule-next').count(),0);await search('3-101');assert.equal(await page.locator('.sp.sel').count(),0);assert.match(await page.locator('#panel').innerText(),/ещё не установлено/);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),null);});
await test('Old raw storage survives first-floor load; manual F1 binding persists and is searchable',async()=>{await fresh();const old={schemaVersion:1,buildingId:map.id,mapDataVersion:map.dataVersion,bindings:{'B3-F4-N01':{spaceId:'B3-F4-N01',floorLevel:4,roomNumber:'405',fullNumber:'3-405',method:'manual',updatedAt:'2026-10-08T05:00:00Z'}}},raw=JSON.stringify(old);await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);await bind('B3-F1-N01','101');const stored=JSON.parse(await page.evaluate(k=>localStorage.getItem(k),KEY));assert.deepEqual(stored.bindings['B3-F4-N01'],old.bindings['B3-F4-N01']);await page.reload();await search('3-101');assert.equal(await page.locator('[data-id="B3-F1-N01"].sel.bound').count(),1);assert.equal(await page.locator('.sp.scheduled-mine').count(),0);});
await test('Transactional export/import round trip retains old and first-floor IDs; cancellation/prototype rejection atomic',async()=>{await fresh();await bind('B3-F1-N01','101');await bind('B3-F1-S13','102');await floor(4);await select('B3-F4-N01');await page.locator('#numInput').fill('405');await page.locator('#numInput').press('Enter');const d=await exportData();assert.equal(d.count,3);await upload({...d,bindings:[{spaceId:'B3-F1-N02',roomNumber:'101'}]});assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),KEY)).bindings['B3-F1-N02'].roomNumber,'101');const transferred=await page.evaluate(k=>localStorage.getItem(k),KEY);accept=false;await upload({...d,bindings:[{spaceId:'B3-F1-N03',roomNumber:'101'}]});assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),transferred);accept=true;await upload({...d,bindings:[{spaceId:'B3-F1-N04',roomNumber:'104'},{spaceId:'__proto__',roomNumber:'105'}]});assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),transferred);await fresh();await upload(d);assert.equal((await exportData()).count,3);const restored=JSON.parse(await page.evaluate(k=>localStorage.getItem(k),KEY)).bindings;assert.equal(restored['B3-F1-N01'].roomNumber,'101');assert.equal(restored['B3-F4-N01'].roomNumber,'405');return {isolatedTestBindings:true,userStorageInspected:false};});
await test('Desktop wheel/pan/buttons retain finite floor-specific viewBox',async()=>{await fresh();const start=await page.locator('#map').getAttribute('viewBox');await page.mouse.move(500,450);await page.mouse.wheel(0,-300);await page.waitForTimeout(120);assert.notEqual(await page.locator('#map').getAttribute('viewBox'),start);const zoom=await page.locator('#map').getAttribute('viewBox');await page.mouse.move(500,450);await page.mouse.down();await page.mouse.move(575,485,{steps:4});await page.mouse.up();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoom);await page.locator('#zoomReset').click();await select('B3-F1-N01');assert.ok((await page.locator('#map').getAttribute('viewBox')).split(' ').every(v=>Number.isFinite(+v)));});
for(const viewport of [{width:390,height:844},{width:320,height:740},{width:844,height:390}])await test('Mobile '+viewport.width+'x'+viewport.height+' actual touch, centered selection, pinch and screenshot',async()=>{await fresh(viewport,true);await select('B3-F1-N09');let p=await point(f.spaces.find(s=>s.id==='B3-F1-N09').labelPoint);await page.touchscreen.tap(p.x,p.y);assert.equal(await page.locator('[data-id="B3-F1-N09"].sel').count(),1);const hit=await page.evaluate(p=>({id:document.elementFromPoint(p.x,p.y)?.closest('[data-id]')?.dataset.id,overflow:document.documentElement.scrollWidth>innerWidth}),p);assert.equal(hit.id,'B3-F1-N09');assert.equal(hit.overflow,false);await page.screenshot({path:path.join(out,'mobile-'+viewport.width+'x'+viewport.height+'.png')});const cdp=await context.newCDPSession(page),r=await page.locator('#mapwrap').boundingBox(),x=r.x+r.width*.4,y=r.y+r.height*.5,start=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-40,y,id:1},{x:x+40,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(+((await page.locator('#map').getAttribute('viewBox')).split(' ')[2])<+(start.split(' ')[2]));const zoom=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y:y+15,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoom);return {viewport,device:'Chrome CDP emulation'};});
await test('All six historical floor SVGs pixel-identical to accepted baseline; first-floor SVG exported',async()=>{for(let n=2;n<=7;n++)assert.deepEqual(await exported(root,n,false),await exported(baseline,n,false),'floor '+n+' unchanged pixels');await exported(root,1,true);});
await test('No runtime exceptions and production model remains immutable',async()=>{await fresh();assert.deepEqual(await page.evaluate(()=>FCIM_MAP_DATA),map);assert.equal(await page.locator('#routeToggle,#layerRoute').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);});
}finally{const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts,results,errors,consoleErrors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));if(context)await context.close();if(browser)await browser.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(e=>{console.error(e);process.exitCode=2});
