// Independent Playwright checks using real rendered classes, text, controls and screen bounds.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||path.join(__dirname,'map01-evidence'));
const fixture=require('../schedule-fixture.js'),map=require('../map-data.js');
const original=process.argv[3]?require(path.join(path.resolve(process.argv[3]),'map-data.js')):null;
fs.mkdirSync(out,{recursive:true});
const files=['index.html','map-data.js','room-contract.js','schedule-engine.js','schedule-fixture.js','map-semantics.js'];
const KEY='fcim-indoor-map/utm-b3/bindings',results=[],errors=[],consoleErrors=[],requests=[];
let browser,context,page,url,tag;
async function fresh({mobile=false,viewport,overrideFixture,noGraph=false,file=false}={}){
  if(context)await context.close();
  context=await browser.newContext({viewport:viewport||(mobile?{width:390,height:844}:{width:1440,height:900}),isMobile:mobile,hasTouch:mobile,acceptDownloads:true});
  if(overrideFixture)await context.route('**/schedule-fixture.js',r=>r.fulfill({contentType:'text/javascript',body:'window.FCIM_SCHEDULE_FIXTURE='+JSON.stringify(overrideFixture)+';'}));
  if(noGraph)await context.route('**/map-data.js',r=>{const data=structuredClone(map);data.floors.forEach(f=>delete f.navigation);delete data.verticalLinks;return r.fulfill({contentType:'text/javascript',body:'window.FCIM_MAP_DATA='+JSON.stringify(data)+';'});});
  page=await context.newPage();page.setDefaultTimeout(5000);
  page.on('pageerror',e=>errors.push({test:tag,message:e.message,stack:e.stack}));
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push({test:tag,message:m.text()});});
  page.on('request',r=>requests.push({test:tag,url:r.url()}));page.on('dialog',d=>d.accept());
  await page.clock.install({time:new Date('2026-10-08T05:30:00Z')});
  await page.goto(file?pathToFileURL(path.join(root,'index.html')).href:url,{waitUntil:'load'});
}
async function test(name,fn){tag=name;const e=errors.length,c=consoleErrors.length;try{const evidence=await fn();assert.equal(errors.length,e,'No page errors');assert.equal(consoleErrors.length,c,'No console errors');results.push({name,status:'PASS',evidence});}catch(err){results.push({name,status:'FAIL',error:err.stack,errors:errors.slice(e)});}console.log(results.at(-1).status,name);}
async function floor(n){await page.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();}
async function time(value){await page.locator('#scheduleTime').fill(value);await page.locator('#scheduleTime').dispatchEvent('change');}
async function date(value){await page.locator('#scheduleDate').fill(value);await page.locator('#scheduleDate').dispatchEvent('change');}
async function select(id){await page.locator('[data-id="'+id+'"]').focus();await page.locator('[data-id="'+id+'"]').press('Enter');}
async function scheduleHighlights(){return page.locator('.sp.scheduled-mine,.sp.scheduled-other,.sp.schedule-next').evaluateAll(ps=>ps.map(p=>p.dataset.id));}
async function summary(){return page.locator('#scheduleSummary').innerText();}
async function mapVisibility(id){return page.evaluate(id=>{const room=document.querySelector('[data-id="'+id+'"]'),r=room.getBoundingClientRect(),m=document.querySelector('#mapwrap').getBoundingClientRect(),s=document.querySelector('#sheet').getBoundingClientRect(),n=document.querySelector('#floorNav').getBoundingClientRect();const center=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {room:r.toJSON(),map:m.toJSON(),sheet:s.toJSON(),nav:n.toJSON(),hit:center?.closest('[data-id]')?.getAttribute('data-id'),overflow:document.documentElement.scrollWidth>innerWidth};},id);}
function visible(v,id){assert.ok(v.room.top>=v.map.top&&v.room.left>=v.map.left&&v.room.right<=v.map.right,'Entire selected outline within map viewport');assert.ok(v.room.bottom<=v.sheet.top&&v.room.bottom<v.nav.top,'Selected outline above sheet and floor controls');assert.equal(v.hit,id,'Actual hit test reaches selected room');assert.equal(v.overflow,false);}
(async()=>{
  const server=http.createServer((req,res)=>{const file=new URL(req.url,'http://local').pathname.slice(1)||'index.html';if(file==='favicon.ico'){res.writeHead(204);return res.end();}if(!files.includes(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,file)));});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/index.html';
  try{
    browser=await chromium.launch({channel:'chrome',headless:true});console.log('Chrome',browser.version());
    await test('Initial My Group selects and highlights explicitly mapped demo room',async()=>{await fresh();assert.equal(await page.locator('#floorNav .active').innerText(),'4');assert.deepEqual(await scheduleHighlights(),['B3-F4-N05']);assert.equal(await page.locator('[data-id="B3-F4-N05"].sel').count(),1);assert.match(await summary(),/Алгоритмы · демо/);assert.match(await summary(),/08:00–09:30/);});
    for(const n of [2,3,4,5,6,7])await test('Floor '+n+' renders original space count, partitions, doors and structural objects',async()=>{await fresh();await floor(n);const f=map.floors.find(f=>f.level===n);assert.equal(await page.locator('#layerSpaces polygon').count(),f.spaces.length);assert.equal(await page.locator('#layerVert > g').count(),f.geometry.verticals.length);assert.ok(await page.locator('#layerDoors > *').count()>=f.geometry.doors.length);await page.screenshot({path:path.join(out,'floor-'+n+'.png')});return {spaces:f.spaces.length,verticals:f.geometry.verticals.length};});
    await test('Pending first floor and basement keep the valid floor unchanged',async()=>{await fresh();for(const n of ['1','D']){await page.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();assert.equal(await page.locator('#floorNav .active').innerText(),'4');assert.match(await page.locator('#toast').innerText(),/Геометрия не создавалась/);}});
    await test('Routing controls, route layers, Dijkstra and route event handlers are removed',async()=>{await fresh();await select('B3-F4-N01');assert.equal(await page.locator('#routeToggle,#routeFromHere,#routeToHere,#allowLift,#routeSwap,#routeClear,#layerRoute,.route,.route-dash').count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/Маршрут отсюда|Маршрут сюда|Условная стоимость/);const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.doesNotMatch(html,/computeRoute|buildGraph|nodeIndex|setRouteMode|routePanelHtml/);});
    await test('Startup, floor, room selection and schedules work with graph absent',async()=>{await fresh({noGraph:true});await floor(7);await select('B3-F7-N01');await time('10:00');assert.equal(await page.locator('#floorNav .active').innerText(),'6');assert.deepEqual(await scheduleHighlights(),['B3-F6-N01']);await select('B3-F6-EL1');assert.match(await page.locator('#panel').innerText(),/Лифтовая шахта/);});
    await test('Changing group replaces the selected lesson immediately',async()=>{await fresh();await page.locator('#groupSelect').selectOption('SI-DEMO-2');assert.match(await summary(),/Семинар · демо/);assert.doesNotMatch(await summary(),/Алгоритмы · демо/);assert.deepEqual(await scheduleHighlights(),['B3-F4-N05']);});
    await test('Time and period changes select mapped floors and do not leave stale highlights',async()=>{await fresh();await time('10:00');assert.equal(await page.locator('#floorNav .active').innerText(),'6');assert.deepEqual(await scheduleHighlights(),['B3-F6-N01']);await page.locator('#periodSelect').selectOption('0');assert.equal(await page.locator('#scheduleTime').inputValue(),'08:00');assert.equal(await page.locator('#floorNav .active').innerText(),'4');assert.deepEqual(await scheduleHighlights(),['B3-F4-N05']);});
    await test('All Classes aggregates shared room; selecting it shows both subjects and teachers',async()=>{await fresh();await page.locator('#allMode').click();await select('B3-F4-N05');const text=await page.locator('#panel').innerText();for(const value of ['3-405a','TI-DEMO-1','SI-DEMO-2','Алгоритмы · демо','Семинар · демо','Демо-преподаватель A','Демо-преподаватель B','08:00–09:30','Синтетические данные','возможный конфликт'])assert.ok(text.includes(value),value);assert.equal(await page.locator('#panel [data-lesson-id]').count(),2);await page.screenshot({path:path.join(out,'shared-room.png')});});
    await test('All Classes distinguishes the selected group from other scheduled groups',async()=>{await fresh();const f=structuredClone(fixture);f.lessons[1].room='3-601';await fresh({overrideFixture:f});await page.locator('#allMode').click();assert.equal(await page.locator('[data-id="B3-F4-N05"].scheduled-mine').count(),1);await floor(6);assert.equal(await page.locator('[data-id="B3-F6-N01"].scheduled-other').count(),1);await page.locator('#groupSelect').selectOption('SI-DEMO-2');assert.equal(await page.locator('[data-id="B3-F6-N01"].scheduled-mine').count(),1);});
    await test('Rendered highlight fills match the legend, even when selection is cleared',async()=>{const f=structuredClone(fixture);f.lessons[1].room='3-601';await fresh({overrideFixture:f});await page.locator('#allMode').click();await floor(6);assert.equal(await page.locator('[data-id="B3-F6-N01"]').evaluate(p=>getComputedStyle(p).fill),'rgb(219, 234, 254)');await floor(4);assert.equal(await page.locator('[data-id="B3-F4-N05"]').evaluate(p=>getComputedStyle(p).fill),'rgb(167, 231, 206)');});
    await test('Unmapped 3-609 gives explicit feedback and never selects arbitrary polygon',async()=>{await fresh();await page.locator('#groupSelect').selectOption('SI-DEMO-2');await time('12:00');assert.match(await summary(),/3-609/);assert.match(await summary(),/Location not mapped yet/);assert.deepEqual(await scheduleHighlights(),[]);assert.equal(await page.locator('.sp.sel').count(),0);await page.locator('#allMode').click();assert.match(await summary(),/Location not mapped yet/);});
    await test('Lesson without room remains visible without stale highlight',async()=>{await fresh();await page.locator('#groupSelect').selectOption('SI-DEMO-2');await time('10:00');assert.match(await summary(),/Проект · демо/);assert.match(await summary(),/Аудитория не указана/);assert.deepEqual(await scheduleHighlights(),[]);await page.locator('#allMode').click();assert.match(await summary(),/Проект · демо/);});
    await test('Subgroups choose their own lesson and another building is never highlighted',async()=>{await fresh();await time('12:00');await page.locator('#subgroupSelect').selectOption('1');assert.equal(await page.locator('#floorNav .active').innerText(),'2');assert.deepEqual(await scheduleHighlights(),['B3-F2-S03']);await page.locator('#subgroupSelect').selectOption('2');assert.match(await summary(),/2-405/);assert.match(await summary(),/Другой корпус/);assert.deepEqual(await scheduleHighlights(),[]);await page.locator('#allMode').click();assert.doesNotMatch(await summary(),/Практика · демо/);assert.match(await summary(),/исключённых из карты: 1/);});
    await test('Odd/even day changes immediately replace floor and active record',async()=>{await fresh();await time('14:00');assert.equal(await page.locator('#floorNav .active').innerText(),'6');assert.match(await summary(),/Нечётная неделя/);await date('2026-10-15');assert.equal(await page.locator('#floorNav .active').innerText(),'7');assert.match(await summary(),/Чётная неделя/);assert.deepEqual(await scheduleHighlights(),['B3-F7-N01']);});
    await test('No active lesson displays next lesson with a distinct future highlight',async()=>{await fresh();await time('09:40');assert.match(await summary(),/Нет активного занятия/);assert.match(await summary(),/Следующее занятие/);assert.equal(await page.locator('[data-id="B3-F6-N01"].schedule-next').count(),1);assert.equal(await page.locator('.sp.scheduled-mine').count(),0);});
    await test('No next lesson at coverage end and outside-coverage feedback are explicit',async()=>{await fresh();await date('2027-06-27');await time('20:00');assert.match(await summary(),/Следующее занятие.*не найдено/);assert.deepEqual(await scheduleHighlights(),[]);await date('2027-06-28');assert.match(await summary(),/Дата вне заданного периода/);});
    await test('Current-time mode uses fixed UTC instant as Europe/Chisinau and recalculates at minute boundary',async()=>{await fresh();await page.locator('#currentTime').click();assert.equal(await page.locator('#scheduleDate').inputValue(),'2026-10-08');assert.equal(await page.locator('#scheduleTime').inputValue(),'08:30');assert.equal(await page.locator('#scheduleTime').isDisabled(),true);await page.clock.fastForward(60*60*1000);assert.equal(await page.locator('#scheduleTime').inputValue(),'09:30');assert.equal(await page.locator('[data-id="B3-F6-N01"].schedule-next').count(),1);await page.locator('#selectedTime').click();assert.equal(await page.locator('#scheduleTime').isDisabled(),false);});
    await test('Demo does not persist bindings or overwrite existing localStorage; search remains production-only',async()=>{await fresh();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),null);await page.locator('#searchInput').fill('405a');await page.locator('#searchInput').press('Enter');assert.match(await page.locator('#panel').innerText(),/ещё не установлено/);assert.equal(await page.locator('.sp.sel').count(),0);const store={schemaVersion:1,buildingId:'utm-b3',mapDataVersion:map.dataVersion,bindings:{'B3-F4-N01':{spaceId:'B3-F4-N01',floorLevel:4,roomNumber:'405a',fullNumber:'3-405a',method:'manual',updatedAt:'2026-10-08T05:00:00Z'}}};const raw=JSON.stringify(store);await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);assert.equal(await page.locator('[data-id="B3-F4-N05"].scheduled-mine').count(),1);assert.equal(await page.locator('[data-id="B3-F4-N01"].bound').count(),1);await page.locator('#searchInput').fill('3-405A');await page.locator('#searchInput').press('Enter');assert.equal(await page.locator('[data-id="B3-F4-N01"].sel').count(),1);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);});
    await test('Export contains only user bindings and no synthetic associations',async()=>{await fresh();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);const exportData=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exportData.count,0);assert.deepEqual(exportData.bindings,[]);});
    await test('Incomplete records and duplicate conflicts remain diagnosed in UI without page exceptions',async()=>{const f=structuredClone(fixture);f.lessons.push({...f.lessons[0],subject:'Conflicting subject'});f.lessons.push({id:'missing-fields'});await fresh({overrideFixture:f});await page.locator('#allMode').click();assert.match(await summary(),/Неполные или конфликтующие записи: 3/);await select('B3-F4-N05');assert.equal(await page.locator('#panel [data-lesson-id]').count(),3);assert.match(await page.locator('#panel').innerText(),/Conflicting subject/);});
    await test('Facilities communicate unknown operation and do not invent toilet markers',async()=>{await fresh();await select('B3-F4-EL1');assert.match(await page.locator('#panel').innerText(),/Лифтовая шахта/);assert.match(await page.locator('#panel').innerText(),/operation: unknown/);assert.equal(await page.locator('[data-facility="toilet"]').count(),0);assert.match(await page.locator('#panel').innerText(),/Туалеты, входы и работа лифтов не подтверждены/);});
    await test('In-browser rendering does not mutate original geometry, identities or graph metadata',async()=>{await fresh();for(const n of [2,3,4,5,6,7])await floor(n);const data=await page.evaluate(()=>JSON.parse(JSON.stringify(FCIM_MAP_DATA)));assert.deepEqual(data,map);});
    for(const viewport of [{width:390,height:844},{width:320,height:740},{width:844,height:390}])await test('Mobile selected polygon remains visible after sheet settles '+viewport.width+'x'+viewport.height,async()=>{
      await fresh({mobile:true,viewport});await page.waitForTimeout(350);visible(await mapVisibility('B3-F4-N05'),'B3-F4-N05');
      await page.locator('#grip').click();await page.waitForTimeout(350);await floor(4);const b=await page.locator('[data-id="B3-F4-N01"]').boundingBox();await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);await page.waitForTimeout(350);
      assert.equal(await page.locator('[data-id="B3-F4-N01"].sel').count(),1);const v=await mapVisibility('B3-F4-N01');visible(v,'B3-F4-N01');
      const card=await page.locator('#panel > .card').first().boundingBox();assert.ok(card.y>=v.sheet.top+30&&card.y<v.sheet.bottom-40,'Selected room card is revealed inside the sheet');
      await page.screenshot({path:path.join(out,'mobile-'+viewport.width+'x'+viewport.height+'.png')});return v;
    });
    await test('Mobile selecting a south room or schedule-driven floor also survives panel expansion',async()=>{await fresh({mobile:true});await select('B3-F4-S16');await page.waitForTimeout(350);visible(await mapVisibility('B3-F4-S16'),'B3-F4-S16');await time('10:00');await page.waitForTimeout(350);const v=await mapVisibility('B3-F6-N01');visible(v,'B3-F6-N01');return v;});
    await test('Desktop wheel, pan and zoom reset remain operational',async()=>{await fresh();const original=await page.locator('#map').getAttribute('viewBox');await page.mouse.move(450,450);await page.mouse.wheel(0,-400);await page.waitForTimeout(100);const zoomed=await page.locator('#map').getAttribute('viewBox');assert.notEqual(zoomed,original);await page.mouse.move(470,470);await page.mouse.down();await page.mouse.move(560,510,{steps:5});await page.mouse.up();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoomed);await page.locator('#zoomReset').click();assert.ok((await page.locator('#map').getAttribute('viewBox')).split(' ').every(v=>Number.isFinite(Number(v))));});
    await test('Mobile pinch and pan work with CDP touch simulation',async()=>{await fresh({mobile:true});const cdp=await context.newCDPSession(page),rect=await page.locator('#mapwrap').boundingBox(),y=rect.y+rect.height*.5;const start=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:150,y,id:1},{x:240,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y,id:1},{x:290,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const pinched=await page.locator('#map').getAttribute('viewBox');assert.ok(Number(pinched.split(' ')[2])<Number(start.split(' ')[2]));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:220,y:y+25,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),pinched);return {mode:'CDP simulated touch, not a physical mobile device'};});
    await test('file:// standalone schedules work with no network or backend',async()=>{await fresh({file:true});await time('10:00');assert.equal(await page.locator('#floorNav .active').innerText(),'6');await page.locator('#allMode').click();assert.match(await summary(),/Проект · демо/);assert.deepEqual(await scheduleHighlights(),['B3-F6-N01']);});
    if(original)await test('Four cleaned polygon renderings are pixel-identical to pre-MAP-01 shapes',async()=>{await fresh();for(const id of ['B3-F2-N08','B3-F3-N08','B3-F4-N08','B3-F5-N07']){const find=d=>d.floors.flatMap(f=>f.spaces).find(s=>s.id===id),before=find(original),after=find(map);const x=Math.min(...before.polygon.map(p=>p[0]))-5,y=Math.min(...before.polygon.map(p=>p[1]))-5,w=Math.max(...before.polygon.map(p=>p[0]))-x+5,h=Math.max(...before.polygon.map(p=>p[1]))-y+5;async function render(s){await page.setContent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="'+[x,y,w,h].join(' ')+'"><polygon points="'+s.polygon.map(p=>p.join(',')).join(' ')+'" fill="#dbeafe" stroke="#123456" stroke-width="1.6" stroke-linejoin="round"/></svg>');return page.locator('svg').screenshot();}assert.deepEqual(await render(after),await render(before),id+' identical pixels');}return {polygons:4};});
    await test('Prototype requests only standalone local assets',async()=>assert.ok(requests.every(r=>r.url.startsWith('file:')||r.url.startsWith('http://127.0.0.1:')),JSON.stringify(requests.filter(r=>!r.url.startsWith('file:')&&!r.url.startsWith('http://127.0.0.1:')))));
  }finally{
    const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({browser:browser?.version(),counts,results,errors,consoleErrors,requests},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));
    if(context)await context.close();if(browser)await browser.close();await new Promise(r=>server.close(r));
  }
  process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(e=>{console.error(e);process.exitCode=2});
