// Recorded public producer responses + explicitly synthetic boundary mutations.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const map=require('../map-data.js'),room=require('../room-contract.js'),adapter=require('../timetable-adapter.js'),engine=require('../schedule-engine.js');
const parse=room.createParser(map,'3'),catalog=require('../room-identification.js').createCatalog(map,parse);
const policy=require('../timetable-room-policy.js').createPolicy(map,parse,room.createResolver(map,parse,catalog));
const fixture=course=>({p:structuredClone(require('./fixtures/map02b/course'+course+'-schedule.json')),s:structuredClone(require('./fixtures/map02b/course'+course+'-status.json'))});
const normalize=(f,course=1)=>adapter.normalize(f.p,f.s,course,policy,'2026-10-09T20:03:22Z');
function one(mutator,course=1){const f=fixture(course);f.p.lessons=[f.p.lessons[0]];f.p.count=f.s.schedule.lessons=1;mutator(f.p.lessons[0],f);return f;}
test('recorded public response bytes match the capture manifest',()=>{for(const r of require('./fixtures/map02b/capture.json').responses)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'fixtures/map02b',r.file))).digest('hex'),r.sha256);});
for(const course of [1,2])test('real course '+course+' preserves each event, every membership, metadata and source uncertainty',()=>{
 const f=fixture(course),d=normalize(f,course);assert.equal(d.events.length,f.p.count);assert.equal(d.memberships.length,f.p.lessons.reduce((n,l)=>n+new Set(l.groups).size,0));assert.deepEqual(d.metadata,f.p.metadata);assert.equal(d.schemaVersion,2);assert.ok(d.regularFcim);assert.equal(d.calendar.authority,'configured-unverified');assert.equal(d.calendar.validFrom,undefined);assert.equal(d.calendar.validUntil,undefined);
 for(const e of d.events){const l=f.p.lessons.find(l=>l.id===e.sourceLessonId);assert.equal(e.rawRoom,l.room);assert.equal(e.weekParity,l.week_parity);assert.equal(e.uncertain,l.uncertain);assert.deepEqual(e.sourceLesson,l);}
});
test('wrong root, metadata, status or requested course rejects the whole candidate',()=>{for(const change of [f=>f.p.course_year=2,f=>f.p.metadata.course_year=2,f=>f.s.course_year=2,f=>f.s.schedule.course_year=2]){const f=fixture(1);change(f);assert.throws(()=>normalize(f));}assert.throws(()=>normalize(fixture(1),3));});
for(const key of ['academic_year','semester','source_kind','source_pdf_url','source_pdf_hash','parser_version','downloaded_at','parsed_at'])test('cross-request revision mismatch: '+key,()=>{const f=fixture(1);f.s.schedule[key]='changed';assert.throws(()=>normalize(f),/revision mismatch/);});
test('duplicate source IDs reject even identical duplicate records',()=>{const f=fixture(1);f.p.lessons.push(structuredClone(f.p.lessons[0]));f.p.count++;f.s.schedule.lessons++;assert.throws(()=>normalize(f),/duplicate lesson id/);});
test('shared lesson produces one event with all memberships and one room event',()=>{
 const f=one(l=>{l.groups=fakeGroups(l.groups);l.room='101';l.week_parity='both';l.uncertain=false;l.subgroup=null;});
 function fakeGroups(){return [fGroup(0),fGroup(1)];}function fGroup(i){return fixture(1).p.groups[i];}
 const d=normalize(f),e=adapter.evaluate([d],{date:'2026-10-05',time:'08:15',courseYear:1,group:d.groups[0]});assert.equal(e.active.length,1);assert.equal(d.memberships.length,2);assert.equal(engine.aggregate(e.active,l=>policy.locate(l,[])).rooms[0].lessons.length,1);
});
test('different source IDs at the same time remain distinct, with possible room conflict',()=>{const f=one(l=>{l.room='101';l.uncertain=false;l.week_parity='both';l.subgroup=null;});f.p.lessons.push({...f.p.lessons[0],id:'other-event'});f.p.count=f.s.schedule.lessons=2;const d=normalize(f),e=adapter.evaluate([d],{date:'2026-10-05',time:'08:15'});assert.equal(e.active.length,2);assert.equal(engine.aggregate(e.active,l=>policy.locate(l,[])).rooms[0].lessons.length,2);});
test('revision changes event identity; IDs are also scoped by course',()=>{const f=fixture(1),a=normalize(f);f.p.metadata.source_pdf_hash=f.s.schedule.source_pdf_hash='a'.repeat(64);const b=normalize(f);assert.notEqual(a.events[0].id,b.events[0].id);assert.notEqual(a.events[0].id,normalize(fixture(2),2).events[0].id);});
for(const parity of ['odd','even','both','unknown'])test('calendar retains '+parity+' and unknown never highlights',()=>{const d=normalize(one(l=>{l.week_parity=parity;l.uncertain=false;l.subgroup=null;}));const e=adapter.evaluate([d],{date:'2026-10-05',time:'08:15',courseYear:1,group:d.groups[0]});assert.equal(d.events[0].weekParity,parity);assert.equal(e.active.length,parity==='both'||parity===e.week.parity?1:0);assert.equal(e.unknown.length,parity==='unknown'?1:0);});
test('unidentified half-group and parser uncertainty are visible without confident applicability',()=>{for(const change of [l=>l.subgroup='0.5 gr.',l=>l.uncertain=true]){const d=normalize(one(l=>{l.week_parity='both';l.uncertain=false;l.subgroup=null;change(l);}));const e=adapter.evaluate([d],{date:'2026-10-05',time:'08:15'});assert.equal(e.active.length,0);assert.equal(e.unknown.length,1);}});
test('subgroup filtering keeps whole-group events and exact group membership',()=>{const d=normalize(one(l=>{l.subgroup='2';l.uncertain=false;l.week_parity='both';}));const s={date:'2026-10-05',time:'08:15',courseYear:1,group:d.events[0].groups[0]};assert.equal(adapter.evaluate([d],{...s,subgroup:'1'}).groupActive.length,0);assert.equal(adapter.evaluate([d],{...s,subgroup:'2'}).groupActive.length,1);d.events[0].subgroup=null;assert.equal(adapter.evaluate([d],{...s,subgroup:'1'}).groupActive.length,1);});
test('unknown academic year stays null; no date bounds or semester exclusions are invented',()=>{const f=fixture(1);f.p.metadata.academic_year=f.s.schedule.academic_year=null;const d=normalize(f);assert.equal(d.metadata.academic_year,null);assert.equal(d.events[0].academicYear,null);assert.equal(d.events[0].validFrom,undefined);assert.equal(d.events[0].excludedDates,undefined);});
test('selected civil dates have no weekend look-ahead and use configured Monday only',()=>{assert.equal(adapter.week('2026-10-09','2026-08-31').parity,adapter.week('2026-10-11','2026-08-31').parity);assert.notEqual(adapter.week('2026-10-11','2026-08-31').parity,adapter.week('2026-10-12','2026-08-31').parity);for(const anchor of ['invalid','2026-02-30','2026-09-01'])assert.equal(adapter.week('2026-10-05',anchor),null);});
test('invalid anchor suppresses restricted records but preserves both-week planned events',()=>{const f=one(l=>{l.week_parity='odd';l.uncertain=false;l.subgroup=null;});f.s.source.odd_week_anchor='invalid';let d=normalize(f);assert.equal(adapter.evaluate([d],{date:'2026-10-05',time:'08:15'}).unknown.length,1);f.p.lessons[0].week_parity='both';d=normalize(f);assert.equal(adapter.evaluate([d],{date:'2026-10-05',time:'08:15'}).active.length,1);});
for(const code of ['101','103','106'])test('default Building 3 resolves full user-confirmed composite '+code,()=>{const location=policy.normalize(code,true);const resolved=policy.locate({location},[]);assert.equal(location.roomCode,'3-'+code);assert.equal(location.interpretation,'default-building-3');assert.deepEqual(resolved.spaceIds,catalog.mappings.find(r=>r.roomCode==='3-'+code).spaceIds);assert.equal(resolved.spaceIds.length,2);assert.equal(resolved.provenance,'user-confirmed');assert.equal(resolved.onSiteVerification,'unknown');});
for(const value of ['2-101','101 corp. 2','101 (Building 2)','101 корпус 2'])test('explicit foreign building never resolves to Building 3: '+value,()=>{const l=policy.normalize(value,true);assert.equal(l.buildingId,'utm-b2');assert.equal(l.roomCode,'2-101');assert.equal(l.status,'outside-building');assert.equal(policy.locate({location:l},[]).spaceId,null);});
for(const value of [null,'','101/103','101, 103','101-103','UTM campus 101','101 gym','<img src=x>','3-101 / 2-103'])test('missing, malformed or multiple venue remains unlocated: '+value,()=>{assert.equal(policy.locate({location:policy.normalize(value,true)},[]).spaceId,null);});
test('default is source-specific; examination or unrelated PDF does not inherit Building 3',()=>{assert.equal(policy.normalize('101',false).status,'unknown-building');const f=one(l=>l.room='101');f.p.metadata.source_pdf_url=f.s.schedule.source_pdf_url='https://fcim.utm.md/wp-content/uploads/examinations.pdf';assert.equal(normalize(f).events[0].location.status,'unknown-building');assert.equal(policy.normalize('3-101',false).interpretation,'explicit-building');});
test('upper-floor code is canonical but never guessed from number',()=>{const l=policy.normalize('405',true),r=policy.locate({location:l},[]);assert.equal(l.roomCode,'3-405');assert.equal(r.spaceId,null);});
test('manual catalog conflicts remain active and no demo association is consulted',()=>{const location=policy.normalize('101',true);assert.equal(policy.locate({location},[{spaceId:'B3-F1-S12',roomNumber:'199'}]).status,'ambiguous-binding');const l=policy.normalize('405',true);assert.equal(policy.locate({location:l},[{spaceId:'B3-F4-N01',roomNumber:'405',verification:'unverified'}]).spaceId,null);});
for(const change of [l=>l.day='Sunday',l=>l.start_time='25:99',l=>l.end_time=l.start_time,l=>l.week_parity='all',l=>l.confidence=NaN,l=>l.geometry.x0=Infinity,l=>l.groups=['invented'],l=>l.subject='',l=>l.uncertain='false'])test('reject malformed external record '+change.toString(),()=>{assert.throws(()=>normalize(one(change)));});
test('malicious text remains literal data with no effect on identities or prototype',()=>{const d=normalize(one(l=>{l.subject='<img src=x onerror=alert(1)>';l.teacher='__proto__';l.room='101 <script>'; }));assert.equal(d.events[0].subject,'<img src=x onerror=alert(1)>');assert.equal(policy.locate(d.events[0],[]).spaceId,null);assert.equal({}.polluted,undefined);});
test('partial courses never substitute each other; time interval is half-open',()=>{const d=normalize(one(l=>{l.week_parity='both';l.subgroup=null;l.uncertain=false;}));assert.equal(adapter.evaluate([d],{date:'2026-10-05',time:'08:00',courseYear:2,group:d.groups[0]}).groupActive.length,0);assert.equal(adapter.evaluate([d],{date:'2026-10-05',time:'09:30'}).active.length,0);});
