// Actual Chrome; isolated storage and synthetic injection, never a user's profile.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]),map=require('../map-data.js'),ident=require('../room-identification.js'),KEY='fcim-indoor-map/utm-b3/bindings';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];let browser,context,page,accept=true;
async function fresh(viewport={width:1440,height:900},demo=null){if(context)await context.close();context=await browser.newContext({viewport,isMobile:viewport.width<900,hasTouch:viewport.width<900,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());
 if(demo)await page.addInitScript(({demo})=>{let fixture;Object.defineProperty(window,'FCIM_SCHEDULE_FIXTURE',{get:()=>fixture,set:value=>{const mappings={'101':['S12','S13'],'103':['S10','S11'],'105':['S09'],'106':['N05','N06']};fixture={...value,demoAssociations:Object.entries(mappings).map(([code,ids])=>({roomNumber:code,spaceIds:ids.map(id=>'B3-F1-'+id)})),lessons:Object.keys(mappings).flatMap(code=>['TI-DEMO-1','SI-DEMO-2'].map((group,i)=>({...value.lessons[0],id:'isolated-'+code+'-'+i,group,room:'3-'+code,subject:'Изолированный тест '+code,teacher:null}))) };if(demo==='partial')fixture.demoAssociations=[{roomNumber:'103',spaceId:'B3-F1-S10'}];if(demo==='next')fixture.lessons=fixture.lessons.map(l=>({...l,startTime:'09:50',endTime:'11:20'}));}});},{demo});
 await page.goto(pathToFileURL(path.join(root,'index.html')).href+'#floor=1');}
async function test(name,fn){const n=errors.length;try{const evidence=await fn();assert.equal(errors.length,n);results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
async function search(n){await page.locator('#searchInput').fill(n);await page.locator('#searchInput').press('Enter');}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');await page.waitForTimeout(150);}
async function selected(ids){assert.deepEqual(await page.locator('#layerSpaces .sel').evaluateAll(es=>es.map(e=>e.dataset.id).sort()),ids.slice().sort());}
async function point(pt){return page.locator('#map').evaluate((s,pt)=>{const p=new DOMPoint(...pt).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},pt);}
async function store(bindings){const raw=JSON.stringify({schemaVersion:1,buildingId:map.id,mapDataVersion:map.dataVersion,bindings:Object.fromEntries(bindings.map(b=>[b.spaceId,{...b,floorLevel:+b.spaceId.match(/-F(\d)/)[1],fullNumber:'3-'+b.roomNumber,method:'manual',updatedAt:'2026-10-09T07:00:00Z'}]))});await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();return raw;}
async function exportData(){const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);return JSON.parse(fs.readFileSync(await d.path(),'utf8'));}
async function upload(bindings){await page.locator('#importFile').setInputFiles({name:'room01b.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'fcim-indoor-map/room-bindings',schemaVersion:1,buildingId:map.id,mapSchemaVersion:map.schemaVersion,mapDataVersion:map.dataVersion,bindings}))});await page.waitForTimeout(150);}
async function artwork(source,n,box,name){const [, ,vw,vh]=box.split(' ').map(Number),width=vw>500?2080:Math.round(680*vw/vh),height=vw>500?440:680;const p=await browser.newPage({viewport:{width:Math.max(2080,width),height:Math.max(900,height)}});await p.goto(pathToFileURL(path.join(source,'index.html')).href+'#floor='+n);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,{box,width,height})=>{const c=s.cloneNode(true),a=[s,...s.querySelectorAll('*')],b=[c,...c.querySelectorAll('*')];a.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','pointer-events','paint-order'])b[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width',String(width));c.setAttribute('height',String(height));c.setAttribute('viewBox',box);c.setAttribute('xmlns','http://www.w3.org/2000/svg');c.style=`width:${width}px;height:${height}px;background:white;overflow:hidden`;return c.outerHTML;},{box,width,height});await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.locator('svg').screenshot();if(name){fs.writeFileSync(path.join(out,name+'.svg'),svg);fs.writeFileSync(path.join(out,name+'.png'),png);}await p.close();return png;}
(async()=>{try{browser=await chromium.launch({channel:'chrome',headless:true});
await test('F1 overview keeps all fifteen labels once and all source mappings intact',async()=>{await fresh();assert.equal(await page.locator('[data-room-label]').count(),15);assert.equal(await page.locator('[data-room-label="3-103"]').count(),1);assert.equal(await page.locator('[data-room-label="3-103"]').textContent(),'103');for(const n of ['101','103','105','106']){await search(n);const r=ident.inventory.find(r=>r.roomCode==='3-'+n);await selected(r.spaceIds);}await page.locator('#zoomReset').click();await page.screenshot({path:path.join(out,'desktop-overview.png')});});
await test('Storage S07/N10/STEN is neutral, hidden from focus, API selection and discovery',async()=>{await fresh();for(const id of ['S07','N10','STEN']){const p=page.locator('[data-id="B3-F1-'+id+'"]');assert.equal(await p.getAttribute('tabindex'),null);assert.equal(await p.getAttribute('role'),null);assert.equal(await p.evaluate(e=>getComputedStyle(e).pointerEvents),'none');await page.evaluate(id=>FCIM_MAP_APP.selectSpace('B3-F1-'+id),id);await selected([]);}assert.equal(await page.locator('#map').getByText(/склад|S07/i).count(),0);});
await test('No storage doors or opening hints; WC, reception and eastern main entrance remain',async()=>{await fresh();for(const id of ['B3-F1-S07-D1','B3-F1-S07-D2','B3-F1-N10-D1'])assert.equal(await page.locator('[data-door-id="'+id+'"]').count(),0);assert.equal(await page.locator('[data-opening-id="B3-F1-OPEN-STEN"]').count(),0);for(const id of ['B3-F1-S06-D1','B3-F1-S08-D1','B3-F1-S14-D1'])assert.equal(await page.locator('[data-door-id="'+id+'"]').count(),1);assert.equal(await page.locator('[data-opening-id="B3-F1-OPEN-STES"]').count(),1);assert.equal(await page.locator('[data-main-entrance]').textContent(),'↤ Главный вход');});
await test('103 has one left entry and one qualified internal door; no false corridor/right-neighbor doors',async()=>{await fresh();for(const id of ['B3-F1-S11-D1','B3-F1-S11-D2'])assert.equal(await page.locator('[data-door-id="'+id+'"]').count(),0);const left=page.locator('[data-door-id="B3-F1-S10-D1"] .door-gap'),inside=page.locator('[data-door-id="B3-F1-S10-S11-INTERNAL"] .door-gap');assert.equal(+await left.getAttribute('x'),551.5);assert.equal(+await inside.getAttribute('x'),568.4);assert.equal(+await inside.getAttribute('y'),146);assert.equal(+await inside.getAttribute('height'),14);assert.equal(await page.locator('[data-door-id="B3-F1-S10-S11-INTERNAL"]').getAttribute('data-coordinate-accuracy'),'approximate');await search('103');await page.locator('#panel details summary').first().click();assert.match(await page.locator('#panel').innerText(),/точная геометрия неизвестна/);assert.match(await page.locator('#panel').innerText(),/63b940b7fdfff2ba/);});
await test('Both 103 components select together by keyboard and pointer without absorbing 105/101',async()=>{await fresh();for(const id of ['B3-F1-S10','B3-F1-S11']){await select(id);await selected(['B3-F1-S10','B3-F1-S11']);const p=await point(id.endsWith('S10')?[555,140]:[585,140]);await page.mouse.click(p.x,p.y);await selected(['B3-F1-S10','B3-F1-S11']);assert.equal(await page.locator('[data-id="B3-F1-S09"].sel,[data-id="B3-F1-S12"].sel').count(),0);}assert.equal(await page.locator('[data-room-label="3-103"]').count(),1);});
await test('WC and adjacent 107/105/103/101/106 pointer selection survive cleanup',async()=>{await fresh();for(const id of ['S06','S08','S05','S09','S10','S12','N05']){const s=map.floors[0].spaces.find(s=>s.id==='B3-F1-'+id);await select(s.id);const p=await point(s.labelPoint);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+s.id+'"].sel').count(),1);}assert.equal(await page.locator('[data-facility-label="toilet"]').count(),2);});
await test('Back-WC neutral fill matches circulation; only three spur edges normalize to 1.6',async()=>{await fresh();const fill=await page.locator('[data-neutral-back-wc]').evaluate(e=>getComputedStyle(e).fill),hall=await page.locator('[data-id="B3-F1-HC"]').evaluate(e=>getComputedStyle(e).fill);assert.equal(fill,hall);assert.equal(await page.locator('.back-wc-wall').count(),1);assert.equal(await page.locator('.back-wc-wall').evaluate(e=>getComputedStyle(e).strokeWidth),'1.6px');assert.equal(await page.locator('.back-wc-wall').getAttribute('points'),'511,175 511,192 459,192 459,175');assert.equal(await page.locator('.exterior-wall').evaluate(e=>getComputedStyle(e).strokeWidth),'4px');assert.equal(await page.locator('#layerBase .outline').evaluate(e=>getComputedStyle(e).stroke),'none');assert.equal(await page.locator('#layerFeat .box,#layerFeat .treads').count(),0);});
await test('Legacy S07 classroom assignment exports unchanged but search is blocked; imports atomic',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-S07',roomNumber:'116'},{spaceId:'B3-F4-N01',roomNumber:'405'}]);await search('116');await selected([]);assert.match(await page.locator('#panel').innerText(),/Конфликт ручной привязки/);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);const d=await exportData();assert.equal(d.count,2);assert.ok(d.bindings.some(b=>b.spaceId==='B3-F1-S07'&&b.roomNumber==='116'));await upload([{spaceId:'B3-F1-N01',roomNumber:'114'},{spaceId:'B3-F1-S07',roomNumber:'116'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);});
await test('Isolated synthetic 103 All/My/Next highlighting keeps two components, one occupancy and label',async()=>{await fresh(undefined,'complete');await page.locator('#allMode').click();const s=await page.evaluate(()=>FCIM_MAP_APP.getScheduleState());const o=s.occupancy.filter(o=>o.roomCode==='3-103');assert.equal(o.length,1);assert.equal(o[0].lessons.length,2);assert.deepEqual(o[0].spaceIds,['B3-F1-S10','B3-F1-S11']);assert.equal(await page.locator('[data-id="B3-F1-S10"].scheduled-mine,[data-id="B3-F1-S11"].scheduled-mine').count(),2);assert.equal(await page.locator('[data-room-label="3-103"]').count(),1);assert.equal(await page.locator('.demo-label').count(),0);await page.locator('#myMode').click();await search('103');await selected(['B3-F1-S10','B3-F1-S11']);await fresh(undefined,'next');assert.equal(await page.locator('[data-id="B3-F1-S10"].schedule-next,[data-id="B3-F1-S11"].schedule-next').count(),2);});
await test('Six upper-floor renders remain pixel identical to frozen B snapshot',async()=>{for(let n=2;n<=7;n++)assert.deepEqual(await artwork(root,n,'-30 -45 1100 285'),await artwork(baseline,n,'-30 -45 1100 285'),'floor '+n);});
await test('Required before/after full/WC/103/eastern storage and mobile evidence exported',async()=>{for(const [name,box] of [['floor1','-20 -15 1160 220'],['wc-storage','415 98 115 105'],['room103','530 98 80 85'],['entrance-storage','920 -5 100 110']]){const actual=box;await artwork(baseline,1,actual,'before-'+name);await artwork(root,1,actual,'after-'+name);}const viewport={width:390,height:844};const before=await browser.newPage({viewport,isMobile:true,hasTouch:true});await before.goto(pathToFileURL(path.join(baseline,'index.html')).href+'#floor=1');await before.screenshot({path:path.join(out,'before-mobile-overview.png')});await before.close();await fresh(viewport);await page.screenshot({path:path.join(out,'after-mobile-overview.png')});await search('103');await page.waitForTimeout(350);await selected(['B3-F1-S10','B3-F1-S11']);const p=await point([585,140]);await page.touchscreen.tap(p.x,p.y);await selected(['B3-F1-S10','B3-F1-S11']);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'mobile-selected-103.png')});});
await test('No JS/console exceptions; immutable production data/fixture and no source export',async()=>{await fresh();assert.deepEqual(await page.evaluate(()=>FCIM_MAP_DATA),map);assert.deepEqual(await page.evaluate(()=>FCIM_SCHEDULE_FIXTURE),require('../schedule-fixture.js'));assert.equal((await exportData()).count,0);assert.deepEqual(errors,[]);});
}finally{const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts,results,errors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));if(context)await context.close();if(browser)await browser.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(e=>{console.error(e);process.exitCode=2;});
