const {sourcePixels}=require('./ui01-source-pixels.cjs');
// Actual Chrome; isolated storage and synthetic injection, never a user's profile.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]),map=require('../map-data.js'),ident=require('../room-identification.js'),KEY='fcim-indoor-map/utm-b3/bindings';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];let browser,context,page,accept=true;
async function fresh(viewport={width:1440,height:900},demo=null){if(context)await context.close();context=await browser.newContext({viewport,isMobile:viewport.width<900,hasTouch:viewport.width<900,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());
 if(demo)await page.addInitScript(({demo})=>{let fixture;Object.defineProperty(window,'FCIM_SCHEDULE_FIXTURE',{get:()=>fixture,set:value=>{const mappings={'101':['S12','S13'],'103':['S10','S11'],'105':['S09'],'106':['N05','N06']};fixture={...value,demoAssociations:Object.entries(mappings).map(([code,ids])=>({roomNumber:code,spaceIds:ids.map(id=>'B3-F1-'+id)})),lessons:Object.keys(mappings).flatMap(code=>['TI-DEMO-1','SI-DEMO-2'].map((group,i)=>({...value.lessons[0],id:'isolated-'+code+'-'+i,group,room:'3-'+code,subject:'Изолированный тест '+code,teacher:null}))) };if(demo==='partial')fixture.demoAssociations=[{roomNumber:'103',spaceId:'B3-F1-S10'}];if(demo==='next')fixture.lessons=fixture.lessons.map(l=>({...l,startTime:'09:50',endTime:'11:20'}));}});},{demo});
 await page.goto(pathToFileURL(path.join(root,'index.html')).href+'#floor=1');}
async function test(name,fn){const n=errors.length;try{const evidence=await fn();assert.equal(errors.length,n);results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
async function search(n){await page.locator('#searchInput').fill(n);await page.locator('#searchInput').press('Enter');}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');await page.waitForTimeout(150);}
async function selected(ids){assert.deepEqual(await page.locator('#layerSpaces .sel').evaluateAll(es=>es.map(e=>e.dataset.id).sort()),ids.slice().sort());}
async function point(pt){return page.locator('#map').evaluate((s,pt)=>{const p=new DOMPoint(...pt).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},pt);}
async function store(bindings){const raw=JSON.stringify({schemaVersion:1,buildingId:map.id,mapDataVersion:map.dataVersion,bindings:Object.fromEntries(bindings.map(b=>[b.spaceId,{...b,floorLevel:+b.spaceId.match(/-F(\d)/)[1],fullNumber:'3-'+b.roomNumber,method:'manual',updatedAt:'2026-10-09T07:00:00Z'}]))});await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();return raw;}
async function exportData(){const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);return JSON.parse(fs.readFileSync(await d.path(),'utf8'));}
async function upload(bindings){await page.locator('#importFile').setInputFiles({name:'room01b.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'fcim-indoor-map/room-bindings',schemaVersion:1,buildingId:map.id,mapSchemaVersion:map.schemaVersion,mapDataVersion:map.dataVersion,bindings}))});await page.waitForTimeout(150);}
async function artwork(source,n,box,name){const p=await browser.newPage({viewport:{width:2080,height:600}});await p.goto(pathToFileURL(path.join(source,'index.html')).href+'#floor='+n);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,box)=>{const c=s.cloneNode(true),a=[s,...s.querySelectorAll('*')],b=[c,...c.querySelectorAll('*')];a.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','pointer-events','paint-order'])b[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width','2080');c.setAttribute('height','440');c.setAttribute('viewBox',box);c.setAttribute('xmlns','http://www.w3.org/2000/svg');c.style='width:2080px;height:440px;background:white';return c.outerHTML;},box);await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.locator('svg').screenshot();if(name){fs.writeFileSync(path.join(out,name+'.svg'),svg);fs.writeFileSync(path.join(out,name+'.png'),png);}await p.close();return png;}
(async()=>{try{browser=await chromium.launch({channel:'chrome',headless:true});
await test('Desktop full map: 15 plain numeric labels once and intact facilities',async()=>{await fresh();assert.equal(await page.locator('[data-room-label]').count(),15);for(const r of ident.inventory){assert.equal(await page.locator('[data-room-label="'+r.roomCode+'"]').textContent(),r.roomCode.slice(2));assert.equal(await page.locator('[data-room-label="'+r.roomCode+'"]').count(),1);}assert.equal(await page.locator('[data-facility-label="toilet"]').count(),2);assert.equal(await page.locator('[data-main-entrance]').textContent(),'Главный вход');await page.screenshot({path:path.join(out,'desktop-overview.png')});});
await test('All fifteen searches select complete component sets with one canonical card',async()=>{await fresh();for(const r of ident.inventory){await search(r.roomCode);await selected(r.spaceIds);for(const id of r.spaceIds)assert.equal(await page.locator('[data-id="'+id+'"].flash').count(),1);assert.equal((await page.evaluate(()=>FCIM_MAP_APP.getLogicalSelection())).roomCode,r.roomCode);assert.match(await page.locator('#panel h3').first().innerText(),new RegExp(r.roomCode));for(const id of r.spaceIds)assert.match(await page.locator('#panel').innerText(),new RegExp(id));}assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),null);});
await test('Every composite component supports keyboard and real pointer selection',async()=>{await fresh();for(const r of ident.inventory.filter(r=>r.spaceIds.length>1))for(const id of r.spaceIds){await select(id);await selected(r.spaceIds);const s=map.floors[0].spaces.find(s=>s.id===id),p=await point(s.labelPoint);await page.mouse.click(p.x,p.y);await selected(r.spaceIds);const selection=await page.evaluate(()=>FCIM_MAP_APP.getLogicalSelection());assert.equal(selection.clickedSpaceId,id);assert.equal(selection.roomCode,r.roomCode);}await page.screenshot({path:path.join(out,'desktop-composite-selected.png')});});
await test('101 union selection outline has no shared divider; 103 and 106 walls retained',async()=>{await fresh();await search('101');assert.equal(await page.locator('[data-logical-room="3-101"]').count(),1);const points=await page.locator('[data-logical-room="3-101"]').getAttribute('points');assert.ok(!points.includes('631,105 631,175'));for(const id of ['S12','S13'])assert.equal(await page.locator('[data-id="B3-F1-'+id+'"]').evaluate(e=>getComputedStyle(e).stroke),'none');const walls=await page.evaluate(()=>FCIM_SCHEMATIC_LAYOUT.createFloor(FCIM_MAP_DATA.floors[0],FCIM_ROOM_IDENTIFICATION.createCatalog(FCIM_MAP_DATA,FCIM_ROOM_CONTRACT.createParser(FCIM_MAP_DATA,'3'))).walls.map(l=>l.flat()));assert.ok(!walls.some(a=>a[0]===631&&a[2]===631));assert.ok(walls.some(a=>a[0]===570&&a[2]===570));assert.ok(walls.some(a=>a[0]===540&&a[2]===540));});
await test('103 and 106 doorway evidence remains archived while all door drawings are omitted',async()=>{await fresh();await search('103');await page.locator('#panel details summary').first().click();assert.match(await page.locator('#panel').innerText(),/точная геометрия неизвестна/);assert.equal(await page.locator('[data-door-id],.door-gap').count(),0);assert.equal(await page.evaluate(()=>FCIM_ROOM_IDENTIFICATION.doorQualifications.find(q=>q.id==='B3-F1-S11-D2').connectivityStatus),'qualification-required');assert.deepEqual(await page.evaluate(()=>{const d=FCIM_MAP_DATA.floors[0].geometry.doors.find(d=>d.id==='B3-F1-N05-D1');return [d.x,d.y,d.to];}),[540,57,'B3-F1-N06']);assert.equal(await page.evaluate(()=>FCIM_ROOM_IDENTIFICATION.createCatalog(FCIM_MAP_DATA,FCIM_ROOM_CONTRACT.createParser(FCIM_MAP_DATA,'3')).presentation.qualifiedDoorways.find(d=>d.id==='B3-F1-S10-S11-INTERNAL').coordinateAccuracy),'approximate');});
await test('F1 main stairs and elevators have flat solid polygons without labels, X or treads',async()=>{await fresh();assert.equal(await page.locator('#layerVert text,#layerVert line,#layerVert .treads,#layerVert .x,[data-stair-art]').count(),0);assert.equal(await page.locator('#layerVert [role="button"]').count(),5);for(const id of ['STW','STM','SH1','SH2','STW-INNER']){const p=page.locator('[data-id="B3-F1-'+id+'"] .box');assert.equal(await p.count(),1);assert.equal(await p.evaluate(e=>getComputedStyle(e).stroke),'none');assert.ok(!((await p.evaluate(e=>getComputedStyle(e).fill)).includes('url(')));}assert.equal(await page.locator('#layerFeat .box,#layerFeat .treads').count(),0);});
await test('Western elevator detail discloses reported outage alone; existing shaft reused',async()=>{await fresh();await select('B3-F1-STW-INNER');assert.match(await page.locator('#panel').innerText(),/reported-out-of-service/);assert.match(await page.locator('#panel').innerText(),/независимая проверка не проводилась/);const records=await page.evaluate(()=>FCIM_MAP_APP.getFacilities());assert.deepEqual(records.find(x=>x.id==='B3-F1-STW-INNER').polygon,map.floors[0].geometry.verticals.find(v=>v.id==='B3-F1-STW').innerShaft);for(const id of ['SH1','SH2']){await select('B3-F1-'+id);assert.match(await page.locator('#panel').innerText(),/operation: unknown/);}});
await test('Eastern regions share fill, boundary absent and STES selects reception',async()=>{await fresh();for(const id of ['STES','STEN']){const p=page.locator('[data-id="B3-F1-'+id+'"]');assert.equal(await p.getAttribute('role'),null);assert.equal(await p.getAttribute('tabindex'),null);}const fill=async id=>page.locator('[data-id="B3-F1-'+id+'"]'+(id.startsWith('ST')?' .box':'')).evaluate(e=>getComputedStyle(e).fill);assert.equal(await fill('STES'),await fill('S14'));assert.equal(await fill('STEN'),await fill('N10'));await page.evaluate(()=>FCIM_MAP_APP.selectSpace('B3-F1-STES'));assert.equal(await page.locator('#panel h3').first().innerText(),'Вахта');assert.deepEqual((await page.evaluate(()=>FCIM_MAP_APP.getLogicalSelection())).spaceIds,['B3-F1-S14','B3-F1-STES']);const p=await point([965,155]);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('#panel h3').first().innerText(),'Вахта');});
await test('Storage integrated area cannot be selected or found; entrance and WC remain',async()=>{await fresh();for(const id of ['N10','STEN']){await page.evaluate(id=>FCIM_MAP_APP.selectSpace(id),'B3-F1-'+id);assert.equal(await page.locator('.sp.sel').count(),0);assert.equal(await page.locator('[data-id="B3-F1-'+id+'"]').evaluate(e=>getComputedStyle(e).pointerEvents),'none');}assert.equal(await page.locator('#map').getByText(/склад|STEN|STES/i).count(),0);assert.equal(await page.locator('[data-facility-label="reception"]').textContent(),'Вахта');});
await test('Compatible legacy record remains at original component on load and export',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-N06',roomNumber:'106'}]);await search('106');await selected(['B3-F1-N05','B3-F1-N06']);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);const exported=await exportData();assert.equal(exported.count,1);assert.equal(exported.bindings[0].spaceId,'B3-F1-N06');await page.reload();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);const raw101=await store([{spaceId:'B3-F1-S13',roomNumber:'101'}]);await search('101');await selected(['B3-F1-S12','B3-F1-S13']);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw101);assert.equal((await exportData()).bindings[0].spaceId,'B3-F1-S13');});
await test('Composite conflict preserves raw bytes and blocks both classrooms until explicit resolution',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-S12',roomNumber:'103'}]);for(const n of ['101','103']){await search(n);await selected([]);assert.match(await page.locator('#panel').innerText(),/Конфликт ручной привязки/);}assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);accept=false;await page.locator('[data-remove-conflict]').first().click();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);accept=true;await page.locator('[data-remove-conflict]').first().click();await search('101');await selected(['B3-F1-S12','B3-F1-S13']);});
await test('Transactional imports: accepted component transfer, cancel and prototype/facility rejection',async()=>{await fresh();await store([{spaceId:'B3-F1-N05',roomNumber:'106'},{spaceId:'B3-F4-N01',roomNumber:'405'}]);await upload([{spaceId:'B3-F1-N06',roomNumber:'106'}]);const raw=await page.evaluate(k=>localStorage.getItem(k),KEY),b=JSON.parse(raw).bindings;assert.ok(!b['B3-F1-N05']);assert.equal(b['B3-F1-N06'].roomNumber,'106');assert.equal(b['B3-F4-N01'].roomNumber,'405');accept=false;await upload([{spaceId:'B3-F1-N05',roomNumber:'106'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);accept=true;for(const invalid of ['__proto__','constructor','toString','B3-F1-N10','B3-F1-S14']){await upload([{spaceId:'B3-F1-S09',roomNumber:'105'},{spaceId:invalid,roomNumber:'103'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);}});
await test('Isolated synthetic All Classes and My Group highlight complete sets, one occupancy per code',async()=>{await fresh(undefined,'complete');await page.locator('#allMode').click();const state=await page.evaluate(()=>FCIM_MAP_APP.getScheduleState());assert.equal(state.evaluation.active.length,8);assert.equal(state.occupancy.length,4);for(const o of state.occupancy){assert.equal(o.lessons.length,2);assert.equal(o.spaceIds.length,o.roomCode==='3-105'?1:2);}assert.equal(await page.locator('.sp.scheduled-mine').count(),7);assert.equal(await page.locator('#layerLabels .demo-label').count(),0);assert.equal(await page.locator('[data-room-label]').count(),15);assert.equal(await page.locator('[data-logical-room].schedule-shared').count(),4);await page.locator('#myMode').click();await select('B3-F1-S11');assert.equal(await page.locator('#panel [data-lesson-id]').count(),2);assert.equal(await page.locator('.sp.scheduled-mine').count(),7);await page.screenshot({path:path.join(out,'isolated-synthetic-composites.png')});return {isolatedSynthetic:true,productionFixtureUnchanged:true,realTimetableConnected:false};});
await test('Isolated synthetic next lesson highlights every component with one logical outline',async()=>{await fresh(undefined,'next');const state=await page.evaluate(()=>FCIM_MAP_APP.getScheduleState());assert.equal(state.evaluation.active.length,0);assert.equal(state.upcoming,true);assert.equal(await page.locator('.sp.schedule-next').count(),7);assert.equal(await page.locator('[data-logical-room]').count(),4);});
await test('Partial synthetic composite rejected without borrowing real source or manual records',async()=>{await fresh(undefined,'partial');await page.locator('#allMode').click();assert.equal(await page.locator('.sp.scheduled-mine,.sp.scheduled-other').count(),0);assert.equal((await page.evaluate(()=>FCIM_MAP_APP.getScheduleState())).occupancy.find(o=>o.roomCode==='3-103').status,'invalid-binding');assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),null);});
for(const viewport of [{width:390,height:844},{width:320,height:740},{width:844,height:390}])await test('Mobile '+viewport.width+'x'+viewport.height+' composite search/tap, navigation, touch pan/pinch',async()=>{await fresh(viewport);await page.screenshot({path:path.join(out,'mobile-'+viewport.width+'x'+viewport.height+'-overview.png')});await search('103');await page.waitForTimeout(350);await selected(['B3-F1-S10','B3-F1-S11']);const p=await point([585,140]);await page.touchscreen.tap(p.x,p.y);await selected(['B3-F1-S10','B3-F1-S11']);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'mobile-'+viewport.width+'x'+viewport.height+'-selected.png')});const cdp=await context.newCDPSession(page),r=await page.locator('#mapwrap').boundingBox(),x=r.x+r.width*.5,y=r.y+r.height*.45,start=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-40,y,id:1},{x:x+40,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(+(await page.locator('#map').getAttribute('viewBox')).split(' ')[2]<+start.split(' ')[2]);const zoom=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y:y+15,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoom);await page.locator('#floorNav button').filter({hasText:/^7$/}).click();assert.equal(await page.locator('#floorNav .active').innerText(),'7');await page.locator('#floorNav button').filter({hasText:/^1$/}).click();return {viewport,touch:'Chrome CDP emulation'};});
await test('Six upper floors source layouts remain pixel identical to frozen pre-B working tree',async()=>{for(let n=2;n<=7;n++)assert.deepEqual(await sourcePixels(browser,root,n),await sourcePixels(browser,baseline,n),'floor '+n);});
await test('Before/after overview and all required detailed comparisons exported',async()=>{for(const [name,box] of [['floor1','-20 -15 1160 220'],['room101','590 98 170 85'],['room103','530 98 80 85'],['room105','505 98 40 85'],['room106','503 -5 75 85'],['west-stair-elevator','178 98 77 85'],['wc-cleanup','410 98 92 100'],['east-cleanup','915 -5 100 185'],['elevators-flat','742 0 50 75']]){const actual=box;await artwork(baseline,1,actual,'before-'+name);await artwork(root,1,actual,'after-'+name);}});
await test('No JS exceptions, immutable production data/fixture and source-free export',async()=>{await fresh();assert.deepEqual(await page.evaluate(()=>FCIM_MAP_DATA),map);assert.deepEqual(await page.evaluate(()=>FCIM_SCHEDULE_FIXTURE),require('../schedule-fixture.js'));assert.equal((await exportData()).count,0);assert.deepEqual(errors,[]);});
}finally{const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts,results,errors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));if(context)await context.close();if(browser)await browser.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(e=>{console.error(e);process.exitCode=2;});
