// Preserve all historical ROOM-01A assertions on exact reverse-projected source.
// Current ROOM-01B semantics are tested directly in room01b-data/browser.cjs.
const assert=require('assert/strict'),fs=require('fs'),map=require('../map-data.js'),ident=require('./room01b-contract.cjs').baselineModule('room-identification.js'),room=require('../room-contract.js'),sem=require('../map-semantics.js'),g=require('./geo02-geometry.cjs');
const parse=room.createParser(map,'3'),c=ident.createCatalog(map,parse),f=map.floors[0],results=[];
function test(name,fn){try{results.push({name,status:'PASS',evidence:fn()});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
test('Exact GEO-02 baseline and source allowlist preserve protected bytes',()=>require('./room01-contract.cjs').validatePreservation());
test('All 15 user codes are accounted for; no invented inventory numbers',()=>assert.deepEqual(c.inventory.map(r=>r.roomCode).sort(),['101','102','103','104','105','106','107','108','109','110','111','112','113','114','115'].map(n=>'3-'+n).sort()));
test('Twelve unique one-to-one mappings target valid classroom candidates',()=>{assert.equal(c.mappings.length,12);assert.equal(new Set(c.mappings.map(r=>r.roomCode)).size,12);assert.equal(new Set(c.mappings.map(r=>r.spaceId)).size,12);for(const r of c.mappings){assert.equal(parse(r.roomCode).full,r.roomCode);assert.equal(r.oneToOne,true);assert.ok(c.classroomCandidate(r.spaceId));assert.equal(r.evidence.onSiteVerification,'unknown');}});
test('106, 105 and 103 keep complete candidate sets and no arbitrary fragment binding',()=>{assert.deepEqual(c.inventory.filter(r=>r.status==='unresolved').map(r=>[r.roomCode,r.candidateSpaceIds]),[['3-106',['B3-F1-N05','B3-F1-N06']],['3-105',['B3-F1-S09','B3-F1-S10']],['3-103',['B3-F1-S11','B3-F1-S12']]]);for(const r of c.inventory.filter(r=>r.status==='unresolved'))assert.equal(r.spaceId,null);assert.ok(!c.effective([]).some(r=>['3-106','3-105','3-103'].includes(r.roomCode)));});
test('Two WC are side cells, middle cell is unassigned; gender and access unknown',()=>{const wc=c.identities.filter(x=>x.kind==='toilet');assert.deepEqual(wc.map(x=>x.id),['B3-F1-S06','B3-F1-S08']);assert.equal(c.identity('B3-F1-S07'),null);for(const x of wc){assert.equal(x.label,'WC');assert.equal(c.classroomCandidate(x.id),false);assert.ok(c.checkNewBinding(x.id,'116'));}});
test('Cafe/reception correctly located; storage remains neutral and non-discoverable',()=>{assert.equal(c.identity('B3-F1-N09').label,'Orange Cafe');assert.equal(c.identity('B3-F1-S14').label,'Вахта');assert.equal(c.identity('B3-F1-N10').kind,'storage');assert.equal(c.identity('B3-F1-N10').public,false);assert.equal(c.identity('B3-F1-N10').label,null);for(const id of ['N09','N10','S14'])assert.ok(c.checkNewBinding('B3-F1-'+id,'116'));});
test('East opening alone is main entrance; existing observed coordinates preserved',()=>{const a=sem.facilities(map,c),entrance=a.find(x=>x.id==='B3-F1-OPEN-E');assert.equal(entrance.kind,'entrance');assert.equal(entrance.side,'east');assert.equal(entrance.identitySource,'user-statement-east');assert.deepEqual(entrance.line,[[1000,78],[1000,98]]);assert.equal(entrance.access,'unknown');assert.equal(entrance.geometrySource,'floor1.jpg');for(const id of ['OPEN-W','OPEN-S'])assert.notEqual(a.find(x=>x.id==='B3-F1-'+id).entranceStatus,'main-entrance');});
test('User identity of two lifts never becomes evidence of operation or on-site survey',()=>{const a=sem.facilities(map,c).filter(x=>x.id==='B3-F1-SH1'||x.id==='B3-F1-SH2');assert.equal(a.length,2);for(const x of a){assert.equal(x.kind,'elevator-shaft');assert.equal(x.identityEvidence,'user-confirmed');assert.equal(x.operational,'unknown');assert.equal(x.onSiteVerification,'unknown');}});
test('Source layer is pure, preserves manual records, and reports both conflict directions',()=>{const b=[{spaceId:'B3-F1-N01',roomNumber:'116'},{spaceId:'B3-F4-N01',roomNumber:'112'}],old=JSON.stringify(b),conf=c.conflicts(b);assert.equal(conf.length,2);assert.equal(JSON.stringify(b),old);assert.ok(!c.effective(b).some(x=>['B3-F1-N01','B3-F1-N02','B3-F4-N01'].includes(x.spaceId)));assert.ok(c.checkNewBinding('B3-F1-N01','116'));assert.ok(c.checkNewBinding('B3-F4-N01','112'));});
test('Legacy facility assignment is retained as conflict but never as effective classroom',()=>{const b=[{spaceId:'B3-F1-N10',roomNumber:'116'}];assert.equal(c.conflicts(b).length,1);assert.ok(!c.effective(b).some(x=>x.spaceId===b[0].spaceId));assert.equal(b[0].roomNumber,'116');});
test('Duplicate guards and prototype keys remain fail-closed at the source layer',()=>{for(const id of ['__proto__','constructor','toString','B3-F1-HE'])assert.ok(c.checkNewBinding(id,'116'));assert.equal(c.checkNewBinding('B3-F1-N01',' 3 — 114 '),null);assert.equal(c.checkNewBinding('B3-F4-N01','405a'),null);});
test('All model polygons/ID order unchanged; no new overlap, invalid geometry or identity migration',()=>{for(const p of [f.geometry.outline,f.geometry.corridor,...f.spaces.map(s=>s.polygon)])g.valid(p);for(let i=0;i<f.spaces.length;i++)for(const s of f.spaces.slice(i+1))assert.equal(g.overlap(f.spaces[i].polygon,s.polygon),0);assert.equal(f.spaces.length,28);assert.equal(map.floors.flatMap(f=>f.spaces).length,222);});
test('Physical walls deduplicated and no partitions across confirmed open eastern hall',()=>{const walls=ident.physicalWalls(f);assert.equal(new Set(walls.map(x=>JSON.stringify(x))).size,walls.length);assert.ok(!walls.some(([a,b])=>a[1]===100&&b[1]===100&&Math.min(a[0],b[0])<930&&Math.max(a[0],b[0])>815));assert.ok(!walls.some(([a,b])=>a[1]===100&&b[1]===100&&Math.min(a[0],b[0])<815&&Math.max(a[0],b[0])>750));assert.ok(walls.some(([a,b])=>a[0]===750&&b[0]===750));assert.ok(walls.some(([a,b])=>a[0]===780&&b[0]===780));assert.ok(walls.some(([a,b])=>a[0]===816&&b[0]===816));});
test('All room edges remain physically covered; openings use existing evidence only',()=>{const walls=[...ident.physicalWalls(f),...f.geometry.outline.map((a,i)=>[a,f.geometry.outline[(i+1)%f.geometry.outline.length]])];for(const s of f.spaces.filter(s=>s.kind==='room'))for(let i=0;i<s.polygon.length;i++){const a=s.polygon[i],b=s.polygon[(i+1)%s.polygon.length];for(const t of [0,.25,.5,.75,1]){const p=[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];assert.ok(walls.some(([a,b])=>g.on(p,a,b)),s.id+' boundary');}}});
test('Synthetic fixture and resolver remain independent of user identity mappings',()=>{const fixture=require('../schedule-fixture.js'),resolve=room.createResolver(map,parse);assert.ok(!fixture.demoAssociations.some(x=>x.spaceId.startsWith('B3-F1-')));assert.equal(resolve({room:'114',source:'mock',buildingId:map.id},{demoAssociations:fixture.demoAssociations}).spaceId,null);});
const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify({counts,results},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));process.exitCode=counts.FAIL?1:0;
