// Chrome, isolated storage, real SVG hit tests and CDP touch; no user profile.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]),map=require('../map-data.js'),ident=require('../room-identification.js'),KEY='fcim-indoor-map/utm-b3/bindings';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];let browser,context,page,accept=true;
async function fresh(mobile=false){if(context)await context.close();context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());await page.goto(pathToFileURL(path.join(root,'index.html')).href+'#floor=1');}
async function test(name,fn){const n=errors.length;try{const evidence=await fn();assert.equal(errors.length,n);results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
async function search(value){await page.locator('#searchInput').fill(value);await page.locator('#searchInput').press('Enter');}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');await page.waitForTimeout(120);}
async function point(pt){return page.locator('#map').evaluate((s,pt)=>{const p=new DOMPoint(...pt).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},pt);}
async function exportData(){const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);return JSON.parse(fs.readFileSync(await d.path(),'utf8'));}
async function upload(bindings){const d={format:'fcim-indoor-map/room-bindings',schemaVersion:1,buildingId:map.id,mapSchemaVersion:map.schemaVersion,mapDataVersion:map.dataVersion,bindings};await page.locator('#importFile').setInputFiles({name:'room01.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await page.waitForTimeout(120);}
async function store(bindings){const raw=JSON.stringify({schemaVersion:1,buildingId:map.id,mapDataVersion:map.dataVersion,bindings:Object.fromEntries(bindings.map(b=>[b.spaceId,{...b,floorLevel:+b.spaceId.match(/-F(\d)/)[1],fullNumber:'3-'+b.roomNumber,method:'manual',updatedAt:'2026-10-09T07:00:00Z'}]))});await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();return raw;}
async function artwork(source,n,box,name){const p=await browser.newPage({viewport:{width:2080,height:600}});await p.goto(pathToFileURL(path.join(source,'index.html')).href+'#floor='+n);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,box)=>{const c=s.cloneNode(true),a=[s,...s.querySelectorAll('*')],b=[c,...c.querySelectorAll('*')];a.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','pointer-events','paint-order'])b[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width','2080');c.setAttribute('height','440');c.setAttribute('viewBox',box);c.setAttribute('xmlns','http://www.w3.org/2000/svg');c.style='width:2080px;height:440px;background:white';return c.outerHTML;},box);await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.locator('svg').screenshot();if(name){fs.writeFileSync(path.join(out,name+'.svg'),svg);fs.writeFileSync(path.join(out,name+'.png'),png);}await p.close();return png;}
(async()=>{try{browser=await chromium.launch({channel:'chrome',headless:true});
await test('Desktop floor1 overview, all 7 floors, source numbers and east entrance',async()=>{await fresh();assert.equal(await page.locator('#layerSpaces polygon').count(),28);assert.equal(await page.locator('#layerLabels .lbl').filter({hasText:/^1[0-9]{2}$/}).count(),15);assert.equal(await page.locator('[data-main-entrance]').textContent(),'↤ Главный вход');await page.screenshot({path:path.join(out,'desktop-overview.png')});});
await test('All fifteen canonical searches select every logical component, display source and Floor 1',async()=>{await fresh();for(const r of ident.inventory.filter(r=>r.status==='mapped')){await search(r.roomCode);for(const id of r.spaceIds)assert.equal(await page.locator('[data-id="'+id+'"].sel').count(),1);assert.match(await page.locator('#panel h3').first().innerText(),new RegExp(r.roomCode));assert.match(await page.locator('#panel').innerText(),/разметка пользователя/);assert.equal(await page.locator('#floorNav .active').innerText(),'1');}await search('102');await page.locator('#panel details summary').first().click();assert.match(await page.locator('#panel').innerText(),/488159f6243075d6/);});
await test('Previously unresolved codes now select their complete confirmed component sets',async()=>{await fresh();for(const code of ['3-106','3-105','3-103']){await search(code);assert.equal(await page.locator('.sp.sel').count(),ident.inventory.find(r=>r.roomCode===code).spaceIds.length);assert.match(await page.locator('#panel h3').first().innerText(),new RegExp(code));}await search('116');assert.equal(await page.locator('[data-room-search]').count(),15);});
await test('Source layer never writes localStorage or exports its fifteen bindings',async()=>{await fresh();for(const code of ['114','112','101'])await search(code);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),null);assert.equal((await exportData()).count,0);});
await test('Two WC, cafe and reception pointer selections show names and prohibit binding',async()=>{await fresh();for(const [id,label] of [['S06','WC'],['S08','WC'],['N09','Orange Cafe'],['S14','Вахта']]){await select('B3-F1-'+id);assert.equal(await page.locator('#panel h3').first().innerText(),label);if(await page.locator('#editToggle').getAttribute('aria-pressed')!=='true')await page.locator('#editToggle').click();assert.equal(await page.locator('#numInput,#startEdit').count(),0);const s=map.floors[0].spaces.find(s=>s.id==='B3-F1-'+id),p=await point(s.labelPoint);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+s.id+'"].sel').count(),1);}assert.equal(await page.locator('[data-facility-label="toilet"]').count(),2);});
await test('Storage is neutral, has no public label/focus/binding and cannot be selected',async()=>{await fresh();const s=page.locator('[data-id="B3-F1-N10"]');assert.equal(await s.getAttribute('tabindex'),null);assert.equal(await s.evaluate(e=>getComputedStyle(e).pointerEvents),'none');assert.equal(await page.locator('#map').getByText(/Склад/i).count(),0);await page.evaluate(()=>FCIM_MAP_APP.selectSpace('B3-F1-N10'));assert.equal(await page.locator('.sp.sel').count(),0);});
await test('Observed east opening alone is main entrance, access remains unknown',async()=>{await fresh();const a=await page.evaluate(()=>FCIM_MAP_APP.getFacilities());const e=a.find(x=>x.id==='B3-F1-OPEN-E');assert.equal(e.entranceStatus,'main-entrance');assert.equal(e.identityEvidence,'user-confirmed');assert.equal(e.access,'unknown');for(const id of ['OPEN-W','OPEN-S'])assert.notEqual(a.find(x=>x.id==='B3-F1-'+id).entranceStatus,'main-entrance');assert.equal(await page.locator('#routeToggle,#layerRoute').count(),0);});
await test('Open hall fill has no border; physical walls and structural artwork do not intercept clicks',async()=>{await fresh();for(const id of ['HE','HW','LH','HC']){const p=page.locator('[data-id="B3-F1-'+id+'"]');assert.equal(await p.evaluate(e=>getComputedStyle(e).stroke),'none');assert.equal(await p.evaluate(e=>getComputedStyle(e).pointerEvents),'none');}assert.ok((await page.locator('#layerWalls line').evaluateAll(es=>es.map(e=>getComputedStyle(e).pointerEvents))).every(x=>x==='none'));assert.ok((await page.locator('[data-stair-art]').evaluateAll(es=>es.map(e=>getComputedStyle(e).pointerEvents))).every(x=>x==='none'));});
await test('Persisted source conflict keeps raw bytes, blocks false search and cancellation is atomic',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-N01',roomNumber:'101'},{spaceId:'B3-F4-N01',roomNumber:'405'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);await search('114');assert.equal(await page.locator('.sp.sel').count(),0);assert.match(await page.locator('#panel').innerText(),/Конфликт ручной привязки/);assert.equal((await exportData()).count,2);accept=false;await page.locator('[data-remove-conflict]').first().click();assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);accept=true;await page.locator('[data-remove-conflict]').first().click();await search('114');assert.equal(await page.locator('[data-id="B3-F1-N01"].sel').count(),1);assert.equal((await exportData()).bindings[0].roomNumber,'405');});
await test('Legacy storage assignment survives as explicit conflict, never as classroom',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-N10',roomNumber:'116'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);await search('116');assert.equal(await page.locator('.sp.sel').count(),0);assert.match(await page.locator('#panel').innerText(),/Конфликт ручной привязки/);assert.equal((await exportData()).count,1);});
await test('Import source conflicts, facilities and prototype records are rejected atomically',async()=>{await fresh();const raw=await store([{spaceId:'B3-F4-N01',roomNumber:'405'}]);for(const b of [{spaceId:'B3-F1-N01',roomNumber:'116'},{spaceId:'B3-F4-N02',roomNumber:'114'},{spaceId:'B3-F1-S06',roomNumber:'116'},{spaceId:'B3-F1-N10',roomNumber:'116'},{spaceId:'__proto__',roomNumber:'116'}]){await upload([{spaceId:'B3-F4-N03',roomNumber:'407'},b]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);}});
await test('Manual binding of unknown upper-floor space still imports/exports and leaves F1 source separate',async()=>{await fresh();await upload([{spaceId:'B3-F4-N02',roomNumber:'406'}]);assert.equal((await exportData()).count,1);await search('406');assert.equal(await page.locator('[data-id="B3-F4-N02"].sel').count(),1);await page.reload();await search('114');assert.equal(await page.locator('[data-id="B3-F1-N01"].sel').count(),1);});
await test('Desktop zoom/pan, narrow labels fit their polygons, no schedule in facilities',async()=>{await fresh();await search('102');const label=page.locator('#layerLabels .lbl').filter({hasText:/^102$/});assert.ok((await label.evaluate(e=>e.getBBox().width))<30);const start=await page.locator('#map').getAttribute('viewBox');await page.locator('#zoomIn').click();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),start);await page.mouse.move(500,500);await page.mouse.down();await page.mouse.move(560,530);await page.mouse.up();assert.ok((await page.locator('#map').getAttribute('viewBox')).split(' ').every(x=>Number.isFinite(+x)));assert.equal(await page.locator('[data-facility].scheduled-mine,[data-facility].scheduled-other,[data-facility].schedule-next').count(),0);});
await test('390x844 overview and selected room, real touch pan/pinch and no horizontal overflow',async()=>{await fresh(true);assert.ok(await page.locator('[data-main-entrance]').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)*e.getScreenCTM().a)>=8.9);await page.screenshot({path:path.join(out,'mobile-overview.png')});await search('114');await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'mobile-selected.png')});const s=map.floors[0].spaces.find(s=>s.id==='B3-F1-N01'),p=await point(s.labelPoint);await page.touchscreen.tap(p.x,p.y);assert.equal(await page.locator('[data-id="B3-F1-N01"].sel').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const cdp=await context.newCDPSession(page),r=await page.locator('#mapwrap').boundingBox(),x=r.x+r.width*.5,y=r.y+r.height*.55,start=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-40,y,id:1},{x:x+40,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(+(await page.locator('#map').getAttribute('viewBox')).split(' ')[2]<+start.split(' ')[2]);const zoom=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y:y+15,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoom);});
await test('Six upper-floor SVGs are pixel-identical to current accepted GEO-02',async()=>{for(let n=2;n<=7;n++)assert.deepEqual(await artwork(root,n,'-30 -45 1100 285'),await artwork(baseline,n,'-30 -45 1100 285'),'floor '+n);});
await test('Before/after, entrance, WC and stair/lift/hall evidence rendered',async()=>{await artwork(baseline,1,'-20 -15 1160 220','before-floor1');await artwork(root,1,'-20 -15 1160 220','after-floor1');await artwork(root,1,'810 -10 350 210','east-entrance-reception');await artwork(root,1,'350 65 230 130','wc-detail');await artwork(root,1,'710 -5 125 190','lift-main-stair');await artwork(root,1,'175 85 150 110','west-stair');await artwork(root,1,'780 55 250 140','open-east-hall');});
await test('Model unchanged in browser and no JavaScript or console errors',async()=>{await fresh();assert.deepEqual(await page.evaluate(()=>FCIM_MAP_DATA),map);assert.deepEqual(errors,[]);});
}finally{fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts:results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}),results,errors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{})));if(context)await context.close();if(browser)await browser.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(e=>{console.error(e);process.exitCode=2;});
