const assert=require('assert/strict'),fs=require('fs'),map=require('../map-data.js'),ident=require('../room-identification.js'),room=require('../room-contract.js'),sem=require('../map-semantics.js'),gate=require('./room01c-contract.cjs');
const parse=room.createParser(map,'3'),c=ident.createCatalog(map,parse),f=map.floors[0],old=gate.baselineModule('room-identification.js'),oldCatalog=old.createCatalog(map,parse),results=[];
function test(name,fn){try{results.push({name,status:'PASS',evidence:fn()});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
test('Exact C byte allowlist and historical B/A/GEO gates with Git line-ending normalization',()=>{for(const file of Object.keys(require('../ROOM-01C_CHANGES.json').baselineFiles)){const bytes=fs.readFileSync(require('path').join(__dirname,'..',file)),lf=bytes.toString('utf8').replaceAll('\r\n','\n');assert.deepEqual(gate.recordedBytes(file,Buffer.from(lf)),gate.recordedBytes(file,bytes));assert.deepEqual(gate.recordedBytes(file,Buffer.from(lf.replaceAll('\n','\r\n'))),gate.recordedBytes(file,bytes));assert.throws(()=>gate.recordedBytes(file,Buffer.from(lf+'\n')),/recorded line count/);}return require('./room01-contract.cjs').validatePreservation();});
test('All fifteen mappings, composite identities and selection sets identical to B',()=>{assert.deepEqual(c.mappings,oldCatalog.mappings);assert.equal(c.mappings.length,15);assert.deepEqual(c.roomForSpace('B3-F1-S11').spaceIds,['B3-F1-S10','B3-F1-S11']);for(const r of c.mappings)for(const id of r.spaceIds)assert.deepEqual(c.selectionIds(id),r.spaceIds);});
test('S07 between WC identified as nonpublic storage solely from C contract',()=>{const x=c.identity('B3-F1-S07');assert.equal(x.kind,'storage');assert.equal(x.public,false);assert.equal(x.label,null);assert.equal(x.evidenceSource,'ROOM-01C user contract');assert.equal(x.evidence.sha256,'431afa9788ea79ec9bd98631f074e4d9ed231dc242f94486da3ed93795c2d346');assert.equal(c.classroomCandidate(x.id),false);assert.ok(c.checkNewBinding(x.id,'116'));const q=sem.facilities(map,c).find(q=>q.id===x.id);assert.equal(q.identitySource,x.evidenceSource);assert.equal(q.onSiteVerification,'unknown');});
test('Every storage-only region rejects classroom ownership and doors in either direction',()=>{for(const id of ['B3-F1-S07','B3-F1-N10','B3-F1-STEN']){assert.ok(c.storageOnly(id));assert.equal(c.classroomCandidate(id),false);assert.equal(c.showDoor({spaceId:id,to:'corridor'}),false);assert.equal(c.showDoor({spaceId:'B3-F1-S10',to:id}),false);assert.ok(!c.effective([]).some(r=>r.spaceIds.includes(id)));}});
test('Legacy S07 assignment preserved as visible conflict without migration',()=>{const b=[{spaceId:'B3-F1-S07',roomNumber:'116',method:'legacy'}],raw=JSON.stringify(b);assert.equal(c.conflicts(b).length,1);assert.ok(!c.effective(b).some(r=>r.roomCode==='3-116'));assert.equal(JSON.stringify(b),raw);});
test('Exact storage doors/opening suppressed while WC/reception/main entrance preserved',()=>{const hidden=f.geometry.doors.filter(d=>!c.showDoor(d)).map(d=>d.id);for(const id of ['B3-F1-S07-D1','B3-F1-S07-D2','B3-F1-N10-D1'])assert.ok(hidden.includes(id));for(const id of ['B3-F1-S06-D1','B3-F1-S08-D1','B3-F1-S14-D1'])assert.ok(c.showDoor(f.geometry.doors.find(d=>d.id===id)));assert.equal(c.showOpening(f.geometry.features.find(x=>x.id==='B3-F1-OPEN-STEN')),false);for(const id of ['B3-F1-OPEN-E','B3-F1-OPEN-STES'])assert.equal(c.showOpening(f.geometry.features.find(x=>x.id===id)),true);});
test('103 displayed with one left corridor entry and a qualified internal opening',()=>{const visible=c.displayDoors(f).filter(d=>c.showDoor(d)&&['B3-F1-S10','B3-F1-S11'].includes(d.spaceId));assert.deepEqual(visible.map(d=>d.id),['B3-F1-S10-D1','B3-F1-S10-S11-INTERNAL']);assert.equal(visible[0].to,'corridor');assert.equal(visible[1].to,'B3-F1-S11');assert.equal(visible[1].x,570);assert.equal(visible[1].coordinateAccuracy,'approximate');assert.equal(c.presentation.room103Source.exactGeometry,'unknown');assert.equal(c.presentation.room103Source.sha256,'63b940b7fdfff2ba46e44e1cd7339e328d37413c7b0c7cb3bed0ba6971b7913c');});
test('103 archive remains byte intact, including historical incorrect connectivity',()=>{assert.equal(f.geometry.doors.find(d=>d.id==='B3-F1-S10-D1').x,550);assert.deepEqual(f.geometry.doors.find(d=>d.id==='B3-F1-S11-D2'),gate.baselineModule('map-data.js').floors[0].geometry.doors.find(d=>d.id==='B3-F1-S11-D2'));assert.equal(f.geometry.doors.find(d=>d.id==='B3-F1-S11-D2').to,'B3-F1-S12');assert.deepEqual(ident.doorQualifications,old.doorQualifications);assert.equal(c.showDoor(f.geometry.doors.find(d=>d.id==='B3-F1-S11-D2')),false);});
test('Physical walls, 103 partition, 106 gap and all original room polygons unchanged',()=>{assert.deepEqual(ident.physicalWalls(f),old.physicalWalls(f));const d=f.geometry.doors.find(d=>d.id==='B3-F1-N05-D1');assert.deepEqual([d.x,d.y,d.to],[540,57,'B3-F1-N06']);assert.equal(map.floors.flatMap(f=>f.spaces).length,222);return gate.validatePreservation();});
test('Back-WC outline reuses every original exterior edge once, normalizes only three',()=>{const paths=ident.exteriorWallPaths(f),normalized=paths.filter(x=>x.kind==='back-wc-wall');assert.equal(normalized.length,1);assert.deepEqual(normalized[0].points,[[511,175],[511,192],[459,192],[459,175]]);const lines=paths.flatMap(p=>p.points.slice(1).map((b,i)=>[p.points[i],b]));assert.deepEqual(lines.map(JSON.stringify).sort(),f.geometry.outline.map((a,i)=>JSON.stringify([a,f.geometry.outline[(i+1)%f.geometry.outline.length]])).sort());});
test('Back-WC neutral fill uses existing hidden feature without new identity or access claim',()=>{assert.equal(c.presentation.backWcFeatureId,'B3-F1-SOUTH-STEPS');const x=sem.facilities(map,c).find(x=>x.id===c.presentation.backWcFeatureId);assert.equal(x.display,'hidden-user-request');assert.equal(x.presentationFill,'neutral-circulation-style');assert.equal(x.access,'unknown');assert.deepEqual(x.polygon,f.geometry.features.find(x=>x.id===c.presentation.backWcFeatureId).polygon);});
test('Presentation door overrides and facility changes cannot spill into upper floors',()=>{for(const floor of map.floors.slice(1))assert.deepEqual(c.displayDoors(floor),floor.geometry.doors);const previous=gate.baselineModule('map-semantics.js').facilities(map,oldCatalog).filter(x=>x.floorId&&x.floorId!=='B3-F1'),current=sem.facilities(map,c).filter(x=>x.floorId&&x.floorId!=='B3-F1');assert.deepEqual(current,previous);});
test('Scheduler, parser/resolver, fixture, navigation and geometry files byte protected',()=>{const crypto=require('crypto'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');for(const file of ['map-data.js','room-contract.js','schedule-engine.js','schedule-fixture.js'])assert.equal(hash(fs.readFileSync(file)),hash(gate.baselineBytes(file)));});
const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify({counts,results},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));process.exitCode=counts.FAIL?1:0;
