// Actual Chrome; isolated storage and synthetic injection, never a user's profile.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]),baseline=path.resolve(process.argv[3]),layout=require('../schematic-layout.js'),map=require('../map-data.js'),ident=require('../room-identification.js'),KEY='fcim-indoor-map/utm-b3/bindings';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];let browser,context,page,accept=true;
async function fresh(viewport={width:1440,height:900},demo=null){if(context)await context.close();context=await browser.newContext({viewport,isMobile:viewport.width<900,hasTouch:viewport.width<900,acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());
 if(demo)await page.addInitScript(({demo})=>{let fixture;Object.defineProperty(window,'FCIM_SCHEDULE_FIXTURE',{get:()=>fixture,set:value=>{const mappings={'101':['S12','S13'],'103':['S10','S11'],'105':['S09'],'106':['N05','N06']};fixture={...value,demoAssociations:Object.entries(mappings).map(([code,ids])=>({roomNumber:code,spaceIds:ids.map(id=>'B3-F1-'+id)})),lessons:Object.keys(mappings).flatMap(code=>['TI-DEMO-1','SI-DEMO-2'].map((group,i)=>({...value.lessons[0],id:'isolated-'+code+'-'+i,group,room:'3-'+code,subject:'Изолированный тест '+code,teacher:null}))) };if(demo==='partial')fixture.demoAssociations=[{roomNumber:'103',spaceId:'B3-F1-S10'}];if(demo==='next')fixture.lessons=fixture.lessons.map(l=>({...l,startTime:'09:50',endTime:'11:20'}));}});},{demo});
 await page.goto(pathToFileURL(path.join(root,'index.html')).href+'#floor=1');}
async function test(name,fn){const n=errors.length;try{const evidence=await fn();assert.equal(errors.length,n);results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(results.at(-1).status,name);}
async function search(n){await page.locator('#searchInput').fill(n);await page.locator('#searchInput').press('Enter');}
async function select(id){const p=page.locator('[data-id="'+id+'"]');await p.focus();await p.press('Enter');await page.waitForTimeout(150);}
async function selected(ids){assert.deepEqual(await page.locator('#layerSpaces .sel').evaluateAll(es=>es.map(e=>e.dataset.id).sort()),ids.slice().sort());}
async function point(pt){return page.locator('#map').evaluate((s,pt)=>{const p=new DOMPoint(...pt).matrixTransform(s.getScreenCTM());return {x:p.x,y:p.y};},pt);}
async function store(bindings){const raw=JSON.stringify({schemaVersion:1,buildingId:map.id,mapDataVersion:map.dataVersion,bindings:Object.fromEntries(bindings.map(b=>[b.spaceId,{...b,floorLevel:+b.spaceId.match(/-F(\d)/)[1],fullNumber:'3-'+b.roomNumber,method:'manual',updatedAt:'2026-10-09T07:00:00Z'}]))});await page.evaluate(({KEY,raw})=>localStorage.setItem(KEY,raw),{KEY,raw});await page.reload();return raw;}
async function exportData(){const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);return JSON.parse(fs.readFileSync(await d.path(),'utf8'));}
async function upload(bindings){await page.locator('#importFile').setInputFiles({name:'room01b.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'fcim-indoor-map/room-bindings',schemaVersion:1,buildingId:map.id,mapSchemaVersion:map.schemaVersion,mapDataVersion:map.dataVersion,bindings}))});await page.waitForTimeout(150);}
async function artwork(source,n,box,name){const [, ,vw,vh]=box.split(' ').map(Number),width=vw>500?2080:Math.round(680*vw/vh),height=vw>500?440:680;const p=await browser.newPage({viewport:{width:Math.max(2080,width),height:Math.max(900,height)}});await p.goto(pathToFileURL(path.join(source,'index.html')).href+'#floor='+n);await p.locator('#scheduleDate').fill('2027-06-28');await p.locator('#scheduleDate').dispatchEvent('change');await p.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();const svg=await p.locator('#map').evaluate((s,{box,width,height})=>{const c=s.cloneNode(true),a=[s,...s.querySelectorAll('*')],b=[c,...c.querySelectorAll('*')];a.forEach((o,i)=>{const st=getComputedStyle(o);for(const k of ['fill','stroke','stroke-width','stroke-dasharray','opacity','font-family','font-size','font-weight','text-anchor','dominant-baseline','pointer-events','paint-order','vector-effect','stroke-linecap','stroke-linejoin'])b[i].style.setProperty(k,st.getPropertyValue(k));});c.setAttribute('width',String(width));c.setAttribute('height',String(height));c.setAttribute('viewBox',box);c.setAttribute('xmlns','http://www.w3.org/2000/svg');c.style=`width:${width}px;height:${height}px;background:white;overflow:hidden`;return c.outerHTML;},{box,width,height});await p.setContent('<body style="margin:0">'+svg+'</body>');const png=await p.locator('svg').screenshot();if(name){fs.writeFileSync(path.join(out,name+'.svg'),svg);fs.writeFileSync(path.join(out,name+'.png'),png);}await p.close();return png;}
const {PNG}=require(process.env.PNGJS_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pngjs');
const catalog=ident.createCatalog(map,require('../room-contract.js').createParser(map,'3')),display=layout.createFloor(map.floors[0],catalog);
const shape=id=>display.polygon(id),anchor=id=>display.labelPoint(id);
async function floor(n){await page.locator('#floorNav button').filter({hasText:new RegExp('^'+n+'$')}).click();}
async function walls(){return page.locator('.map-walls').evaluate(e=>({width:getComputedStyle(e).strokeWidth,color:getComputedStyle(e).stroke,vector:getComputedStyle(e).vectorEffect,cap:getComputedStyle(e).strokeLinecap,events:getComputedStyle(e).pointerEvents}));}
(async()=>{try{browser=await chromium.launch({channel:'chrome',headless:true});
await test('All 15 searches and keyboard selections resolve complete component sets',async()=>{await fresh();for(const r of catalog.mappings){await search(r.roomCode);await selected(r.spaceIds);for(const id of r.spaceIds){await select(id);await selected(r.spaceIds);const focus=await page.locator('[data-id="'+id+'"]').evaluate(e=>({width:getComputedStyle(e).outlineWidth,style:getComputedStyle(e).outlineStyle,tap:getComputedStyle(e).webkitTapHighlightColor}));assert.deepEqual(focus,{width:'2px',style:'solid',tap:'rgba(0, 0, 0, 0)'});}assert.equal(await page.locator('[data-room-label="'+r.roomCode+'"]').count(),1);}});
await test('F1 visible rectangles are their actual hit targets; no legacy room polygons remain',async()=>{await fresh();assert.equal(await page.locator('#layerSpaces polygon,#layerVert polygon').count(),0);assert.equal(await page.locator('[data-id="B3-F1-S07"]').count(),0);for(const [id,p] of Object.entries(display.polygons)){const loc=page.locator('[data-id="'+id+'"]'),rect=await loc.evaluate(e=>{const r=e.tagName==='rect'?e:e.querySelector('rect');return ['x','y','width','height'].map(k=>+r.getAttribute(k));});assert.deepEqual(rect,[p[0][0],p[0][1],p[1][0]-p[0][0],p[2][1]-p[0][1]],id);}});
await test('Rectangle corners, composite divider sides and exact shared walls select the shown room',async()=>{await fresh();for(const r of catalog.mappings.filter(r=>r.spaceIds.length>1))for(const id of r.spaceIds){await select(id);const p=shape(id),pts=[[p[0][0]+.8,p[0][1]+.8],[p[2][0]-.8,p[2][1]-.8],anchor(id)];for(const pt of pts){const hit=await point(pt);assert.equal(await page.evaluate(h=>document.elementFromPoint(h.x,h.y)?.closest('[data-id]')?.dataset.id,hit),id);await page.mouse.click(hit.x,hit.y);await selected(r.spaceIds);}}await search('103');const p=await point([570,140]);const id=await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('[data-id]')?.dataset.id,p);assert.ok(['B3-F1-S10','B3-F1-S11'].includes(id));await page.mouse.click(p.x,p.y);await selected(['B3-F1-S10','B3-F1-S11']);});
await test('WC upper regions formerly occupied by S07 now hit one of exactly two WC rectangles',async()=>{await fresh();assert.equal(await page.locator('[data-facility="toilet"]').count(),2);assert.equal(await page.locator('[data-facility-label="toilet"]').count(),2);for(const [id,pt] of [['S06',[450,115]],['S08',[470,115]]]){await select('B3-F1-'+id);const p=await point(pt);await page.mouse.click(p.x,p.y);await selected(['B3-F1-'+id]);assert.equal(await page.locator('#panel h3').first().innerText(),'WC');await page.locator('#editToggle').click();assert.equal(await page.locator('#numInput').count(),0);await page.locator('#editToggle').click();}assert.equal(await page.locator('.back-wc-wall,[data-neutral-back-wc]').count(),0);});
await test('Elevator squares meet without bands or symbols and keep qualified statuses',async()=>{await fresh();for(const id of ['SH1','SH2']){await select('B3-F1-'+id);const p=await point(anchor('B3-F1-'+id));await page.mouse.click(p.x,p.y);assert.match(await page.locator('#panel').innerText(),/operation: unknown/);}await select('B3-F1-STW-INNER');assert.match(await page.locator('#panel').innerText(),/reported-out-of-service/);assert.equal(await page.locator('#layerVert text,#layerVert line,.treads,.x,[data-stair-art]').count(),0);});
await test('One ordinary wall network on every floor; all fills lack coincident strokes',async()=>{await fresh();for(let n=1;n<=7;n++){await floor(n);assert.equal(await page.locator('#layerWalls .map-walls').count(),1);assert.deepEqual(await walls(),{width:'2px',color:'rgb(56, 67, 79)',vector:'non-scaling-stroke',cap:'butt',events:'none'});assert.ok((await page.locator('#layerSpaces [data-id],#layerVert .box,#layerBase .outline').evaluateAll(es=>es.map(e=>getComputedStyle(e).stroke))).every(s=>s==='none'));assert.equal(await page.locator('#layerDoors > *,[data-door-id],[data-opening-id],.door-gap,.door-mk,.treads,.x,[data-stair-art],#layerVert text').count(),0);}});
await test('Actual raster wall thickness stays within 1–3 pixels at three zoom levels',async()=>{await fresh();const widths=[];for(const delta of [0,-260,-260]){await page.locator('#zoomReset').click();const pt=await point([154,30]);await page.mouse.move(pt.x,pt.y);if(delta)await page.mouse.wheel(0,delta);if(widths.length===2)await page.mouse.wheel(0,delta);const p=await point([154,30]);const png=PNG.sync.read(await page.screenshot());const y=Math.round(p.y);let count=0;for(let x=Math.round(p.x)-6;x<=Math.round(p.x)+6;x++){const i=(y*png.width+x)*4;if(png.data[i]<110&&png.data[i+1]<110&&png.data[i+2]<110)count++;}assert.ok(count>=1&&count<=3,'raster width '+count);widths.push(count);assert.equal((await walls()).width,'2px');}assert.ok(Math.max(...widths)-Math.min(...widths)<=1);return {rasterWidths:widths};});
await test('No stair art, door overlays, storage labels or artificial hall dividers on F1',async()=>{await fresh();assert.equal(await page.locator('#map').getByText(/склад|лестниц|лифт|холл/i).count(),0);assert.equal(await page.locator('[data-main-entrance]').textContent(),'Главный вход');assert.equal(await page.locator('[data-entrance-leader]').count(),0);for(const id of ['S07','N10','STEN']){await page.evaluate(id=>FCIM_MAP_APP.selectSpace('B3-F1-'+id),id);await selected([]);}await search('116');assert.equal(await page.locator('#panel [data-room-search]').count(),15);});
await test('Eastern service stair regions share storage/reception fills without seams or stair symbols',async()=>{await fresh();const fill=async id=>page.locator('[data-id="B3-F1-'+id+'"]').evaluate(e=>getComputedStyle(e.tagName==='rect'?e:e.querySelector('.box')).fill);assert.equal(await fill('STEN'),await fill('N10'));assert.equal(await fill('N10'),await page.locator('#layerBase .outline').evaluate(e=>getComputedStyle(e).fill));assert.equal(await fill('STES'),await fill('S14'));assert.ok(!display.walls.some(([a,b])=>a[1]===b[1]&&[layout.firstFloorRails.upperSplit,layout.firstFloorRails.lowerSplit].includes(a[1])&&Math.min(a[0],b[0])===930&&Math.max(a[0],b[0])===1000));await select('B3-F1-S14');const p=await point([965,155]);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('#panel h3').first().innerText(),'Вахта');assert.equal(await page.locator('[data-facility-label="reception"]').count(),1);});
await test('Synthetic All/My/Next highlights every composite once without duplicated lessons',async()=>{await fresh(undefined,'complete');await page.locator('#allMode').click();const state=await page.evaluate(()=>FCIM_MAP_APP.getScheduleState());assert.equal(state.occupancy.length,4);assert.equal(state.occupancy.flatMap(o=>o.lessons).length,8);for(const r of catalog.mappings.filter(r=>r.spaceIds.length>1)){assert.equal(state.occupancy.filter(o=>o.roomCode===r.roomCode).length,1);for(const id of r.spaceIds)assert.equal(await page.locator('[data-id="'+id+'"].scheduled-mine').count(),1);}assert.equal(await page.locator('.demo-label').count(),0);await page.locator('#myMode').click();await search('101');await selected(['B3-F1-S12','B3-F1-S13']);await page.screenshot({path:path.join(out,'isolated-synthetic-composites.png')});await fresh(undefined,'next');assert.equal(await page.locator('.sp.schedule-next').count(),7);assert.equal(await page.locator('[data-logical-room]').count(),4);});
await test('Compatible manual records survive load, search and export without a display-version migration',async()=>{await fresh();const raw=await store([{spaceId:'B3-F1-S13',roomNumber:'101'},{spaceId:'B3-F4-N01',roomNumber:'405'}]);await search('101');await selected(['B3-F1-S12','B3-F1-S13']);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);const data=await exportData();assert.equal(data.count,2);assert.equal(data.mapDataVersion,map.dataVersion);assert.ok(data.bindings.some(b=>b.spaceId==='B3-F1-S13'));await upload([{spaceId:'B3-F1-S07',roomNumber:'116'},{spaceId:'B3-F4-N02',roomNumber:'406'}]);assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),raw);});
await test('Upper floors render all 194 original hit polygons at unchanged coordinates',async()=>{await fresh();for(const f of map.floors.slice(1)){await floor(f.level);const polygons=await page.locator('#layerSpaces polygon').evaluateAll(es=>es.map(e=>[e.dataset.id,[...e.points].map(p=>[p.x,p.y])]));assert.deepEqual(polygons,f.spaces.map(s=>[s.id,s.polygon]));for(const s of f.spaces.slice(0,2)){await select(s.id);const p=await point(s.labelPoint);await page.mouse.click(p.x,p.y);assert.equal(await page.locator('[data-id="'+s.id+'"].sel').count(),1);}}});
for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:320,height:740},{width:844,height:390}])await test('Viewport '+viewport.width+'x'+viewport.height+' selection, hover/touch, zoom, pan and floor navigation',async()=>{await fresh(viewport);await page.screenshot({path:path.join(out,'after-'+viewport.width+'x'+viewport.height+'-overview.png')});await search('103');await page.waitForTimeout(350);await selected(['B3-F1-S10','B3-F1-S11']);for(const pt of [[541,106],[599,174],[585,140]]){const p=await point(pt);if(viewport.width<900)await page.touchscreen.tap(p.x,p.y);else {await page.mouse.move(p.x,p.y);assert.ok(await page.locator('[data-id="B3-F1-S10"]:hover,[data-id="B3-F1-S11"]:hover').count());await page.mouse.click(p.x,p.y);}await selected(['B3-F1-S10','B3-F1-S11']);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'after-'+viewport.width+'x'+viewport.height+'-selected.png')});const start=await page.locator('#map').getAttribute('viewBox');await page.locator('#zoomIn').click();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),start);const box=await page.locator('#mapwrap').boundingBox(),x=box.x+box.width*.5,y=box.y+box.height*.45;if(viewport.width<900){const cdp=await context.newCDPSession(page),before=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-40,y,id:1},{x:x+40,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(+(await page.locator('#map').getAttribute('viewBox')).split(' ')[2]<+before.split(' ')[2]);const zoom=await page.locator('#map').getAttribute('viewBox');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y:y+15,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.locator('#map').getAttribute('viewBox'),zoom);}else {const before=await page.locator('#map').getAttribute('viewBox');await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+40,y+20);await page.mouse.up();assert.notEqual(await page.locator('#map').getAttribute('viewBox'),before);}await floor(7);assert.equal(await page.locator('#floorNav .active').innerText(),'7');await floor(1);return {viewport,touch:viewport.width<900?'Chrome CDP emulation':'desktop pointer'};});
await test('Required before/after floor and detail screenshots exported from actual rendered SVG',async()=>{for(const [name,n,box] of [['floor1',1,'-20 -15 1160 220'],['wc',1,'420 98 100 85'],['elevators',1,'742 -6 54 88'],['room101',1,'590 98 170 85'],['room103',1,'532 98 76 85'],['room106',1,'502 -7 76 89'],['west-stair-elevator',1,'178 98 77 85'],['entrance-reception',1,'810 -8 310 191'],['floor2',2,'-30 -85 1120 345'],['floor4',4,'-30 -45 1100 285'],['floor7',7,'-30 -45 1100 285']]){await artwork(baseline,n,box,'before-'+name);await artwork(root,n,box,'after-'+name);}for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:320,height:740},{width:844,height:390}]){const p=await browser.newPage({viewport,isMobile:viewport.width<900,hasTouch:viewport.width<900});await p.goto(pathToFileURL(path.join(baseline,'index.html')).href+'#floor=1');await p.screenshot({path:path.join(out,'before-'+viewport.width+'x'+viewport.height+'-overview.png')});await p.close();}});
await test('Zero console/runtime errors and no mutation of production fixture or historical model',async()=>{await fresh();assert.deepEqual(await page.evaluate(()=>FCIM_MAP_DATA),map);assert.deepEqual(await page.evaluate(()=>FCIM_SCHEDULE_FIXTURE),require('../schedule-fixture.js'));assert.equal((await exportData()).count,0);assert.deepEqual(errors,[]);});
}finally{const counts=results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({counts,results,errors,browser:browser?.version()},null,2)+'\n');console.log('TOTAL',JSON.stringify(counts));if(context)await context.close();if(browser)await browser.close();}process.exitCode=results.some(r=>r.status==='FAIL')?1:0;})().catch(e=>{console.error(e);process.exitCode=2;});
